# Modeling {#model}
Text
```{r model1, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Fitting

### Probability Density Function {#pdf}  
The histrogram is really an attempt to visualize the **probability density function** (pdf) for a distribution of univariate data.  The pdf is a mathematical representation of the likelihood of sampling a given value from the distribution, assuming a random draw.  Unlike the histogram (which uses bins to describe counts/frequency for data values), however, the pdf is a continuous function that can be solved at any data value.  A pdf is sometimes expressed empirically (as a numeric approximation) or as an exact analytic equation (in the case normal, lognormal, and other *known* distributional forms). We will discuss the creation and visualization of pdfs in Chapter ... 

How to fit a distribution
### LOESS

## Q-Q Plot (Quantile-Quantile) {#qqplot}

## Linear Models

### Assumptions of Linear Regression

### Diagnostics

### Ordinary Least Squares

### Weighted Least Squares

### Deming Regression

### Calibration