<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 11 Modeling | Engineering Data Analysis in R</title>
  <meta name="description" content="This is an undergraduate technical elective course for mechanical engineers who wish to lean about data analysis using the R programming language." />
  <meta name="generator" content="bookdown 0.41 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 11 Modeling | Engineering Data Analysis in R" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="This is an undergraduate technical elective course for mechanical engineers who wish to lean about data analysis using the R programming language." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 11 Modeling | Engineering Data Analysis in R" />
  
  <meta name="twitter:description" content="This is an undergraduate technical elective course for mechanical engineers who wish to lean about data analysis using the R programming language." />
  

<meta name="author" content="John Volckens" />


<meta name="date" content="2024-11-08" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="measure.html"/>
<link rel="next" href="dist.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Engineering Data Analysis in R</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduction</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#how-to-use-this-book"><i class="fa fa-check"></i><b>1.1</b> How to use this book</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#prerequisites"><i class="fa fa-check"></i><b>1.2</b> Prerequisites</a></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#grading"><i class="fa fa-check"></i><b>1.3</b> Grading</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="index.html"><a href="index.html#grading-for-mech-476"><i class="fa fa-check"></i><b>1.3.1</b> Grading for MECH 476</a></li>
<li class="chapter" data-level="1.3.2" data-path="index.html"><a href="index.html#homework-submission"><i class="fa fa-check"></i><b>1.3.2</b> Homework submission</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="index.html"><a href="index.html#course-set-up"><i class="fa fa-check"></i><b>1.4</b> Course set-up</a>
<ul>
<li class="chapter" data-level="1.4.1" data-path="index.html"><a href="index.html#install-r-and-rstudio"><i class="fa fa-check"></i><b>1.4.1</b> Install R and RStudio</a></li>
<li class="chapter" data-level="1.4.2" data-path="index.html"><a href="index.html#install-git-and-create-a-github-account"><i class="fa fa-check"></i><b>1.4.2</b> Install Git and create a GitHub account</a></li>
<li class="chapter" data-level="1.4.3" data-path="index.html"><a href="index.html#connect-git-github-and-rstudio"><i class="fa fa-check"></i><b>1.4.3</b> Connect Git, GitHub, and RStudio</a></li>
<li class="chapter" data-level="1.4.4" data-path="index.html"><a href="index.html#create-new-project-github-first"><i class="fa fa-check"></i><b>1.4.4</b> Create new project, GitHub first</a></li>
<li class="chapter" data-level="1.4.5" data-path="index.html"><a href="index.html#use-rstudiogithub-system-for-homework-submission"><i class="fa fa-check"></i><b>1.4.5</b> Use RStudio/GitHub system for homework submission</a></li>
<li class="chapter" data-level="1.4.6" data-path="index.html"><a href="index.html#confirm-successful-set-up"><i class="fa fa-check"></i><b>1.4.6</b> Confirm successful set-up</a></li>
<li class="chapter" data-level="1.4.7" data-path="index.html"><a href="index.html#asking-for-help-properly"><i class="fa fa-check"></i><b>1.4.7</b> Asking for help (properly)</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="index.html"><a href="index.html#coursebook"><i class="fa fa-check"></i><b>1.5</b> Coursebook</a>
<ul>
<li class="chapter" data-level="1.5.1" data-path="index.html"><a href="index.html#other-helpful-books-not-required"><i class="fa fa-check"></i><b>1.5.1</b> Other helpful books (not required)</a></li>
</ul></li>
<li class="chapter" data-level="1.6" data-path="index.html"><a href="index.html#acknowledgements"><i class="fa fa-check"></i><b>1.6</b> Acknowledgements</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="rprog1.html"><a href="rprog1.html"><i class="fa fa-check"></i><b>2</b> The R Programming Environment</a>
<ul>
<li class="chapter" data-level="2.1" data-path="rprog1.html"><a href="rprog1.html#ch.-2-objectives"><i class="fa fa-check"></i><b>2.1</b> Ch. 2 Objectives</a></li>
<li class="chapter" data-level="2.2" data-path="rprog1.html"><a href="rprog1.html#r-and-r-studio"><i class="fa fa-check"></i><b>2.2</b> R and R Studio</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="rprog1.html"><a href="rprog1.html#what-is-r"><i class="fa fa-check"></i><b>2.2.1</b> What is R?</a></li>
<li class="chapter" data-level="2.2.2" data-path="rprog1.html"><a href="rprog1.html#free-and-open-source-software"><i class="fa fa-check"></i><b>2.2.2</b> Free and open-source software</a></li>
<li class="chapter" data-level="2.2.3" data-path="rprog1.html"><a href="rprog1.html#what-is-rstudio"><i class="fa fa-check"></i><b>2.2.3</b> What is RStudio?</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="rprog1.html"><a href="rprog1.html#communicating-with-r"><i class="fa fa-check"></i><b>2.3</b> Communicating with R</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="rprog1.html"><a href="rprog1.html#r-sessions-console-and-command-prompt"><i class="fa fa-check"></i><b>2.3.1</b> R sessions, console, and command prompt</a></li>
<li class="chapter" data-level="2.3.2" data-path="rprog1.html"><a href="rprog1.html#r-expressions-function-calls-and-objects"><i class="fa fa-check"></i><b>2.3.2</b> R expressions, function calls, and objects</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="rprog1.html"><a href="rprog1.html#r-scripts"><i class="fa fa-check"></i><b>2.4</b> R scripts</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="rprog1.html"><a href="rprog1.html#commenting-code"><i class="fa fa-check"></i><b>2.4.1</b> Commenting code</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="rprog1.html"><a href="rprog1.html#the-package-system"><i class="fa fa-check"></i><b>2.5</b> The “package” system</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="rprog1.html"><a href="rprog1.html#r-packages"><i class="fa fa-check"></i><b>2.5.1</b> R packages</a></li>
<li class="chapter" data-level="2.5.2" data-path="rprog1.html"><a href="rprog1.html#installing-from-cran"><i class="fa fa-check"></i><b>2.5.2</b> Installing from CRAN</a></li>
<li class="chapter" data-level="2.5.3" data-path="rprog1.html"><a href="rprog1.html#loading-an-installed-package"><i class="fa fa-check"></i><b>2.5.3</b> Loading an installed package</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="rprog1.html"><a href="rprog1.html#rs-most-basic-object-types"><i class="fa fa-check"></i><b>2.6</b> R’s most basic object types</a>
<ul>
<li class="chapter" data-level="2.6.1" data-path="rprog1.html"><a href="rprog1.html#vectors"><i class="fa fa-check"></i><b>2.6.1</b> Vectors</a></li>
<li class="chapter" data-level="2.6.2" data-path="rprog1.html"><a href="rprog1.html#dataframes"><i class="fa fa-check"></i><b>2.6.2</b> Dataframes</a></li>
</ul></li>
<li class="chapter" data-level="2.7" data-path="rprog1.html"><a href="rprog1.html#chapter-2-exercises"><i class="fa fa-check"></i><b>2.7</b> Chapter 2 Exercises</a>
<ul>
<li class="chapter" data-level="2.7.1" data-path="rprog1.html"><a href="rprog1.html#set-1-session-helpfiles-scripts-and-objects"><i class="fa fa-check"></i><b>2.7.1</b> Set 1: Session, helpfiles, scripts, and objects</a></li>
<li class="chapter" data-level="2.7.2" data-path="rprog1.html"><a href="rprog1.html#set-2-loading-and-using-packages"><i class="fa fa-check"></i><b>2.7.2</b> Set 2: Loading and using packages</a></li>
</ul></li>
<li class="chapter" data-level="2.8" data-path="rprog1.html"><a href="rprog1.html#chapter-2-homework"><i class="fa fa-check"></i><b>2.8</b> Chapter 2 Homework</a>
<ul>
<li class="chapter" data-level="2.8.1" data-path="rprog1.html"><a href="rprog1.html#special-swirl-commands"><i class="fa fa-check"></i><b>2.8.1</b> Special <code>swirl</code> commands</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="rprog2.html"><a href="rprog2.html"><i class="fa fa-check"></i><b>3</b> Getting and Cleaning Data</a>
<ul>
<li class="chapter" data-level="3.1" data-path="rprog2.html"><a href="rprog2.html#ch.-3-objectives"><i class="fa fa-check"></i><b>3.1</b> Ch. 3 Objectives</a></li>
<li class="chapter" data-level="3.2" data-path="rprog2.html"><a href="rprog2.html#overview"><i class="fa fa-check"></i><b>3.2</b> Overview</a></li>
<li class="chapter" data-level="3.3" data-path="rprog2.html"><a href="rprog2.html#reading-data-into-r"><i class="fa fa-check"></i><b>3.3</b> Reading data into R</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="rprog2.html"><a href="rprog2.html#reading-local-flat-files"><i class="fa fa-check"></i><b>3.3.1</b> Reading local flat files</a></li>
<li class="chapter" data-level="3.3.2" data-path="rprog2.html"><a href="rprog2.html#reading-in-other-file-types"><i class="fa fa-check"></i><b>3.3.2</b> Reading in other file types</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="rprog2.html"><a href="rprog2.html#directories-and-pathnames"><i class="fa fa-check"></i><b>3.4</b> Directories and pathnames</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="rprog2.html"><a href="rprog2.html#directory-structure"><i class="fa fa-check"></i><b>3.4.1</b> Directory structure</a></li>
<li class="chapter" data-level="3.4.2" data-path="rprog2.html"><a href="rprog2.html#working-directory"><i class="fa fa-check"></i><b>3.4.2</b> Working directory</a></li>
<li class="chapter" data-level="3.4.3" data-path="rprog2.html"><a href="rprog2.html#file-and-directory-pathnames"><i class="fa fa-check"></i><b>3.4.3</b> File and directory pathnames</a></li>
<li class="chapter" data-level="3.4.4" data-path="rprog2.html"><a href="rprog2.html#tangent-paste"><i class="fa fa-check"></i><b>3.4.4</b> Tangent: <code>paste</code></a></li>
<li class="chapter" data-level="3.4.5" data-path="rprog2.html"><a href="rprog2.html#reading-online-flat-files"><i class="fa fa-check"></i><b>3.4.5</b> Reading online flat files</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="rprog2.html"><a href="rprog2.html#data-cleaning"><i class="fa fa-check"></i><b>3.5</b> Data cleaning</a>
<ul>
<li class="chapter" data-level="3.5.1" data-path="rprog2.html"><a href="rprog2.html#renaming-columns"><i class="fa fa-check"></i><b>3.5.1</b> Renaming columns</a></li>
<li class="chapter" data-level="3.5.2" data-path="rprog2.html"><a href="rprog2.html#selecting-columns"><i class="fa fa-check"></i><b>3.5.2</b> Selecting columns</a></li>
<li class="chapter" data-level="3.5.3" data-path="rprog2.html"><a href="rprog2.html#add-or-change-columns"><i class="fa fa-check"></i><b>3.5.3</b> Add or change columns</a></li>
<li class="chapter" data-level="3.5.4" data-path="rprog2.html"><a href="rprog2.html#filtering-to-certain-rows"><i class="fa fa-check"></i><b>3.5.4</b> Filtering to certain rows</a></li>
<li class="chapter" data-level="3.5.5" data-path="rprog2.html"><a href="rprog2.html#base-r-equivalents-to-dplyr-functions"><i class="fa fa-check"></i><b>3.5.5</b> Base R equivalents to <code>dplyr</code> functions</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="rprog2.html"><a href="rprog2.html#merging-data-frames"><i class="fa fa-check"></i><b>3.6</b> Merging Data Frames</a>
<ul>
<li class="chapter" data-level="3.6.1" data-path="rprog2.html"><a href="rprog2.html#row-binding"><i class="fa fa-check"></i><b>3.6.1</b> Row Binding</a></li>
<li class="chapter" data-level="3.6.2" data-path="rprog2.html"><a href="rprog2.html#column-binding-_join"><i class="fa fa-check"></i><b>3.6.2</b> Column Binding (_join)</a></li>
</ul></li>
<li class="chapter" data-level="3.7" data-path="rprog2.html"><a href="rprog2.html#piping"><i class="fa fa-check"></i><b>3.7</b> Piping</a></li>
<li class="chapter" data-level="3.8" data-path="rprog2.html"><a href="rprog2.html#markdowns"><i class="fa fa-check"></i><b>3.8</b> Markdowns</a>
<ul>
<li class="chapter" data-level="3.8.1" data-path="rprog2.html"><a href="rprog2.html#r-markdowns"><i class="fa fa-check"></i><b>3.8.1</b> R Markdowns</a></li>
<li class="chapter" data-level="3.8.2" data-path="rprog2.html"><a href="rprog2.html#header"><i class="fa fa-check"></i><b>3.8.2</b> Header</a></li>
<li class="chapter" data-level="3.8.3" data-path="rprog2.html"><a href="rprog2.html#text"><i class="fa fa-check"></i><b>3.8.3</b> Text</a></li>
<li class="chapter" data-level="3.8.4" data-path="rprog2.html"><a href="rprog2.html#code-chunks"><i class="fa fa-check"></i><b>3.8.4</b> Code Chunks</a></li>
</ul></li>
<li class="chapter" data-level="3.9" data-path="rprog2.html"><a href="rprog2.html#chapter-3-exercises"><i class="fa fa-check"></i><b>3.9</b> Chapter 3 Exercises</a>
<ul>
<li class="chapter" data-level="3.9.1" data-path="rprog2.html"><a href="rprog2.html#set-1-pathnames-and-data-import"><i class="fa fa-check"></i><b>3.9.1</b> Set 1: Pathnames and data import</a></li>
<li class="chapter" data-level="3.9.2" data-path="rprog2.html"><a href="rprog2.html#set-2-data-wrangling-and-piping"><i class="fa fa-check"></i><b>3.9.2</b> Set 2: Data wrangling and piping</a></li>
<li class="chapter" data-level="3.9.3" data-path="rprog2.html"><a href="rprog2.html#set-3-r-markdown"><i class="fa fa-check"></i><b>3.9.3</b> Set 3: R Markdown</a></li>
</ul></li>
<li class="chapter" data-level="3.10" data-path="rprog2.html"><a href="rprog2.html#chapter-3-homework"><i class="fa fa-check"></i><b>3.10</b> Chapter 3 Homework</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="dataviz.html"><a href="dataviz.html"><i class="fa fa-check"></i><b>4</b> Data Visualization with <code>ggplot2</code></a>
<ul>
<li class="chapter" data-level="4.1" data-path="dataviz.html"><a href="dataviz.html#chapter-4-objectives"><i class="fa fa-check"></i><b>4.1</b> Chapter 4 Objectives</a></li>
<li class="chapter" data-level="4.2" data-path="dataviz.html"><a href="dataviz.html#install-and-load-ggplot2"><i class="fa fa-check"></i><b>4.2</b> Install and load <code>ggplot2</code></a></li>
<li class="chapter" data-level="4.3" data-path="dataviz.html"><a href="dataviz.html#steps-to-create-a-ggplot2-object"><i class="fa fa-check"></i><b>4.3</b> Steps to create a <code>ggplot2</code> object</a></li>
<li class="chapter" data-level="4.4" data-path="dataviz.html"><a href="dataviz.html#initializing-a-ggplot2-object"><i class="fa fa-check"></i><b>4.4</b> Initializing a <code>ggplot2</code> object</a></li>
<li class="chapter" data-level="4.5" data-path="dataviz.html"><a href="dataviz.html#plot-aesthetics"><i class="fa fa-check"></i><b>4.5</b> Plot aesthetics</a></li>
<li class="chapter" data-level="4.6" data-path="dataviz.html"><a href="dataviz.html#adding-geoms"><i class="fa fa-check"></i><b>4.6</b> Adding geoms</a>
<ul>
<li class="chapter" data-level="4.6.1" data-path="dataviz.html"><a href="dataviz.html#aesthetic-override-a-warning"><i class="fa fa-check"></i><b>4.6.1</b> Aesthetic override: a warning</a></li>
</ul></li>
<li class="chapter" data-level="4.7" data-path="dataviz.html"><a href="dataviz.html#shapes-and-colors"><i class="fa fa-check"></i><b>4.7</b> Shapes and colors</a></li>
<li class="chapter" data-level="4.8" data-path="dataviz.html"><a href="dataviz.html#scales-useful-plot-edits"><i class="fa fa-check"></i><b>4.8</b> Scales: useful plot edits</a></li>
<li class="chapter" data-level="4.9" data-path="dataviz.html"><a href="dataviz.html#ggplot2-example-1"><i class="fa fa-check"></i><b>4.9</b> <code>ggplot2</code> example 1</a></li>
<li class="chapter" data-level="4.10" data-path="dataviz.html"><a href="dataviz.html#ggplot2-example-2"><i class="fa fa-check"></i><b>4.10</b> <code>ggplot2</code> example 2</a></li>
<li class="chapter" data-level="4.11" data-path="dataviz.html"><a href="dataviz.html#store-and-save-ggplot2-objects"><i class="fa fa-check"></i><b>4.11</b> Store and save <code>ggplot2</code> objects</a></li>
<li class="chapter" data-level="4.12" data-path="dataviz.html"><a href="dataviz.html#getting-help-with-ggplot2"><i class="fa fa-check"></i><b>4.12</b> Getting help with <code>ggplot2</code></a></li>
<li class="chapter" data-level="4.13" data-path="dataviz.html"><a href="dataviz.html#chapter-4-homework"><i class="fa fa-check"></i><b>4.13</b> Chapter 4 Homework</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="eda1.html"><a href="eda1.html"><i class="fa fa-check"></i><b>5</b> Univariate Data Exploration</a>
<ul>
<li class="chapter" data-level="5.1" data-path="eda1.html"><a href="eda1.html#ch.-5-objectives"><i class="fa fa-check"></i><b>5.1</b> Ch. 5 Objectives</a></li>
<li class="chapter" data-level="5.2" data-path="eda1.html"><a href="eda1.html#univar"><i class="fa fa-check"></i><b>5.2</b> Univariate Data</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="eda1.html"><a href="eda1.html#location-dispersion-and-shape"><i class="fa fa-check"></i><b>5.2.1</b> Location, Dispersion, and Shape</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="eda1.html"><a href="eda1.html#quantile"><i class="fa fa-check"></i><b>5.3</b> Quantiles</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="eda1.html"><a href="eda1.html#descriptive-statistics"><i class="fa fa-check"></i><b>5.3.1</b> Descriptive Statistics</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="eda1.html"><a href="eda1.html#univariate-data-visualization"><i class="fa fa-check"></i><b>5.4</b> Univariate Data Visualization</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="eda1.html"><a href="eda1.html#summary-vs.-enumerative-plots"><i class="fa fa-check"></i><b>5.4.1</b> Summary vs. Enumerative Plots</a></li>
<li class="chapter" data-level="5.4.2" data-path="eda1.html"><a href="eda1.html#cumulative-distribution-plot"><i class="fa fa-check"></i><b>5.4.2</b> Cumulative Distribution Plot</a></li>
<li class="chapter" data-level="5.4.3" data-path="eda1.html"><a href="eda1.html#hist"><i class="fa fa-check"></i><b>5.4.3</b> Histogram</a></li>
<li class="chapter" data-level="5.4.4" data-path="eda1.html"><a href="eda1.html#box"><i class="fa fa-check"></i><b>5.4.4</b> Boxplot</a></li>
<li class="chapter" data-level="5.4.5" data-path="eda1.html"><a href="eda1.html#time_series"><i class="fa fa-check"></i><b>5.4.5</b> Time-Series Plot</a></li>
<li class="chapter" data-level="5.4.6" data-path="eda1.html"><a href="eda1.html#autocorr"><i class="fa fa-check"></i><b>5.4.6</b> Autocorrelation Plot</a></li>
<li class="chapter" data-level="5.4.7" data-path="eda1.html"><a href="eda1.html#partial-autocorrelation-plot"><i class="fa fa-check"></i><b>5.4.7</b> Partial Autocorrelation Plot</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="eda1.html"><a href="eda1.html#exploring-data"><i class="fa fa-check"></i><b>5.5</b> Exploring Data</a></li>
<li class="chapter" data-level="5.6" data-path="eda1.html"><a href="eda1.html#chapter-5-homework"><i class="fa fa-check"></i><b>5.6</b> Chapter 5 Homework</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="rprog3.html"><a href="rprog3.html"><i class="fa fa-check"></i><b>6</b> Strings, Dates, and Tidying</a>
<ul>
<li class="chapter" data-level="6.1" data-path="rprog3.html"><a href="rprog3.html#chapter-6-objectives"><i class="fa fa-check"></i><b>6.1</b> Chapter 6 Objectives</a></li>
<li class="chapter" data-level="6.2" data-path="rprog3.html"><a href="rprog3.html#strings"><i class="fa fa-check"></i><b>6.2</b> Strings</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="rprog3.html"><a href="rprog3.html#string-detect-match-subset"><i class="fa fa-check"></i><b>6.2.1</b> String detect, match, subset</a></li>
<li class="chapter" data-level="6.2.2" data-path="rprog3.html"><a href="rprog3.html#regular-expressions"><i class="fa fa-check"></i><b>6.2.2</b> Regular Expressions</a></li>
<li class="chapter" data-level="6.2.3" data-path="rprog3.html"><a href="rprog3.html#string-split-replace"><i class="fa fa-check"></i><b>6.2.3</b> String split, replace</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="rprog3.html"><a href="rprog3.html#dates-and-date-times"><i class="fa fa-check"></i><b>6.3</b> Dates and Date-times</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="rprog3.html"><a href="rprog3.html#dates-and-times-in-base-r"><i class="fa fa-check"></i><b>6.3.1</b> Dates and Times in base R</a></li>
<li class="chapter" data-level="6.3.2" data-path="rprog3.html"><a href="rprog3.html#date-time-formats"><i class="fa fa-check"></i><b>6.3.2</b> Date-time formats</a></li>
<li class="chapter" data-level="6.3.3" data-path="rprog3.html"><a href="rprog3.html#date-time-classes-in-r"><i class="fa fa-check"></i><b>6.3.3</b> Date-time classes in R</a></li>
<li class="chapter" data-level="6.3.4" data-path="rprog3.html"><a href="rprog3.html#reading-and-classifying-date-times"><i class="fa fa-check"></i><b>6.3.4</b> Reading and classifying date-times</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="rprog3.html"><a href="rprog3.html#lubridate"><i class="fa fa-check"></i><b>6.4</b> <code>lubridate</code></a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="rprog3.html"><a href="rprog3.html#parsing-functions-in-lubridate"><i class="fa fa-check"></i><b>6.4.1</b> Parsing functions in <code>lubridate</code></a></li>
<li class="chapter" data-level="6.4.2" data-path="rprog3.html"><a href="rprog3.html#date-time-manipulation-with-lubridate"><i class="fa fa-check"></i><b>6.4.2</b> Date-time manipulation with <code>lubridate</code></a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="rprog3.html"><a href="rprog3.html#tidy-data"><i class="fa fa-check"></i><b>6.5</b> Tidy Data</a></li>
<li class="chapter" data-level="6.6" data-path="rprog3.html"><a href="rprog3.html#chapter-6-exercises"><i class="fa fa-check"></i><b>6.6</b> Chapter 6 Exercises</a>
<ul>
<li class="chapter" data-level="6.6.1" data-path="rprog3.html"><a href="rprog3.html#set-1-data-import-and-manipulation"><i class="fa fa-check"></i><b>6.6.1</b> Set 1: Data import and manipulation</a></li>
<li class="chapter" data-level="6.6.2" data-path="rprog3.html"><a href="rprog3.html#set-2-counting"><i class="fa fa-check"></i><b>6.6.2</b> Set 2: Counting</a></li>
<li class="chapter" data-level="6.6.3" data-path="rprog3.html"><a href="rprog3.html#set-3-weekly-tweets"><i class="fa fa-check"></i><b>6.6.3</b> Set 3: Weekly tweets</a></li>
<li class="chapter" data-level="6.6.4" data-path="rprog3.html"><a href="rprog3.html#are-tweets-correlated-in-time"><i class="fa fa-check"></i><b>6.6.4</b> Are tweets correlated in time?</a></li>
<li class="chapter" data-level="6.6.5" data-path="rprog3.html"><a href="rprog3.html#set-4-csu-vs.-cu"><i class="fa fa-check"></i><b>6.6.5</b> Set 4: CSU vs. CU</a></li>
</ul></li>
<li class="chapter" data-level="6.7" data-path="rprog3.html"><a href="rprog3.html#chapter-6-homework"><i class="fa fa-check"></i><b>6.7</b> Chapter 6 Homework</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="eda2.html"><a href="eda2.html"><i class="fa fa-check"></i><b>7</b> Multivariate Data Exploration</a>
<ul>
<li class="chapter" data-level="7.1" data-path="eda2.html"><a href="eda2.html#chapter-7-objectives"><i class="fa fa-check"></i><b>7.1</b> Chapter 7 Objectives</a></li>
<li class="chapter" data-level="7.2" data-path="eda2.html"><a href="eda2.html#bivariate"><i class="fa fa-check"></i><b>7.2</b> Bivariate Data</a></li>
<li class="chapter" data-level="7.3" data-path="eda2.html"><a href="eda2.html#scatt"><i class="fa fa-check"></i><b>7.3</b> Scatterplot</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="eda2.html"><a href="eda2.html#causality"><i class="fa fa-check"></i><b>7.3.1</b> Causality</a></li>
<li class="chapter" data-level="7.3.2" data-path="eda2.html"><a href="eda2.html#corr"><i class="fa fa-check"></i><b>7.3.2</b> Correlation</a></li>
<li class="chapter" data-level="7.3.3" data-path="eda2.html"><a href="eda2.html#correlation-neq-causation"><i class="fa fa-check"></i><b>7.3.3</b> Correlation <span class="math inline">\(\neq\)</span> causation</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="eda2.html"><a href="eda2.html#exploring-multivariate-data"><i class="fa fa-check"></i><b>7.4</b> Exploring Multivariate Data</a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="eda2.html"><a href="eda2.html#facets"><i class="fa fa-check"></i><b>7.4.1</b> Facets</a></li>
<li class="chapter" data-level="7.4.2" data-path="eda2.html"><a href="eda2.html#colors"><i class="fa fa-check"></i><b>7.4.2</b> Colors</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="eda2.html"><a href="eda2.html#chapter-7-exercises"><i class="fa fa-check"></i><b>7.5</b> Chapter 7 Exercises</a>
<ul>
<li class="chapter" data-level="7.5.1" data-path="eda2.html"><a href="eda2.html#fuel-economy-data"><i class="fa fa-check"></i><b>7.5.1</b> Fuel economy data</a></li>
<li class="chapter" data-level="7.5.2" data-path="eda2.html"><a href="eda2.html#import-and-wrangle-data"><i class="fa fa-check"></i><b>7.5.2</b> Import and wrangle data</a></li>
<li class="chapter" data-level="7.5.3" data-path="eda2.html"><a href="eda2.html#check-data"><i class="fa fa-check"></i><b>7.5.3</b> Check data</a></li>
<li class="chapter" data-level="7.5.4" data-path="eda2.html"><a href="eda2.html#check-for-missing-data"><i class="fa fa-check"></i><b>7.5.4</b> Check for missing data</a></li>
<li class="chapter" data-level="7.5.5" data-path="eda2.html"><a href="eda2.html#visualize-data"><i class="fa fa-check"></i><b>7.5.5</b> Visualize data</a></li>
<li class="chapter" data-level="7.5.6" data-path="eda2.html"><a href="eda2.html#multivariate-time-series"><i class="fa fa-check"></i><b>7.5.6</b> Multivariate time series</a></li>
<li class="chapter" data-level="7.5.7" data-path="eda2.html"><a href="eda2.html#density-plots"><i class="fa fa-check"></i><b>7.5.7</b> Density plots</a></li>
<li class="chapter" data-level="7.5.8" data-path="eda2.html"><a href="eda2.html#more-multivariate-plotting"><i class="fa fa-check"></i><b>7.5.8</b> More multivariate plotting</a></li>
<li class="chapter" data-level="7.5.9" data-path="eda2.html"><a href="eda2.html#practice-questions"><i class="fa fa-check"></i><b>7.5.9</b> Practice questions</a></li>
</ul></li>
<li class="chapter" data-level="7.6" data-path="eda2.html"><a href="eda2.html#chapter-7-homework"><i class="fa fa-check"></i><b>7.6</b> Chapter 7 Homework</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="rprog4.html"><a href="rprog4.html"><i class="fa fa-check"></i><b>8</b> Functional Programming</a>
<ul>
<li class="chapter" data-level="8.1" data-path="rprog4.html"><a href="rprog4.html#ch.-8-objectives"><i class="fa fa-check"></i><b>8.1</b> Ch. 8 Objectives</a></li>
<li class="chapter" data-level="8.2" data-path="rprog4.html"><a href="rprog4.html#what-is-functional-programming"><i class="fa fa-check"></i><b>8.2</b> What is <strong><em>functional programming</em></strong>?</a></li>
<li class="chapter" data-level="8.3" data-path="rprog4.html"><a href="rprog4.html#writng-functions"><i class="fa fa-check"></i><b>8.3</b> Writng Functions</a>
<ul>
<li class="chapter" data-level="8.3.1" data-path="rprog4.html"><a href="rprog4.html#example-function-my_mean"><i class="fa fa-check"></i><b>8.3.1</b> Example Function: my_mean</a></li>
<li class="chapter" data-level="8.3.2" data-path="rprog4.html"><a href="rprog4.html#example-function-import.w.name"><i class="fa fa-check"></i><b>8.3.2</b> Example Function: “import.w.name”</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="rprog4.html"><a href="rprog4.html#the-purrr-package"><i class="fa fa-check"></i><b>8.4</b> The <code>purrr::</code> package</a>
<ul>
<li class="chapter" data-level="8.4.1" data-path="rprog4.html"><a href="rprog4.html#function-mapping"><i class="fa fa-check"></i><b>8.4.1</b> Function Mapping</a></li>
</ul></li>
<li class="chapter" data-level="8.5" data-path="rprog4.html"><a href="rprog4.html#applying-functions-to-multiple-columns-dplyracross"><i class="fa fa-check"></i><b>8.5</b> Applying functions to multiple columns: <code>dplyr::across()</code></a>
<ul>
<li class="chapter" data-level="8.5.1" data-path="rprog4.html"><a href="rprog4.html#using-tidy-select-syntax-to-select-columns"><i class="fa fa-check"></i><b>8.5.1</b> Using <code>&lt;tidy-select&gt;</code> syntax to select columns</a></li>
<li class="chapter" data-level="8.5.2" data-path="rprog4.html"><a href="rprog4.html#examples-dplyracross"><i class="fa fa-check"></i><b>8.5.2</b> Examples <code>dplyr::across()</code></a></li>
</ul></li>
<li class="chapter" data-level="8.6" data-path="rprog4.html"><a href="rprog4.html#homework"><i class="fa fa-check"></i><b>8.6</b> Homework</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="transform.html"><a href="transform.html"><i class="fa fa-check"></i><b>9</b> Transformations and Other Tricks</a>
<ul>
<li class="chapter" data-level="9.1" data-path="transform.html"><a href="transform.html#ch.-9-objectives"><i class="fa fa-check"></i><b>9.1</b> Ch. 9 Objectives</a></li>
<li class="chapter" data-level="9.2" data-path="transform.html"><a href="transform.html#transformation"><i class="fa fa-check"></i><b>9.2</b> Transformation</a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="transform.html"><a href="transform.html#centering"><i class="fa fa-check"></i><b>9.2.1</b> Centering</a></li>
<li class="chapter" data-level="9.2.2" data-path="transform.html"><a href="transform.html#rescaling"><i class="fa fa-check"></i><b>9.2.2</b> Rescaling</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="transform.html"><a href="transform.html#normalization-and-standardization"><i class="fa fa-check"></i><b>9.3</b> Normalization and Standardization</a>
<ul>
<li class="chapter" data-level="9.3.1" data-path="transform.html"><a href="transform.html#rate-normalization"><i class="fa fa-check"></i><b>9.3.1</b> Rate normalization</a></li>
<li class="chapter" data-level="9.3.2" data-path="transform.html"><a href="transform.html#standardizing"><i class="fa fa-check"></i><b>9.3.2</b> Standardizing</a></li>
<li class="chapter" data-level="9.3.3" data-path="transform.html"><a href="transform.html#reducing-skewness"><i class="fa fa-check"></i><b>9.3.3</b> Reducing Skewness</a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="transform.html"><a href="transform.html#stratification"><i class="fa fa-check"></i><b>9.4</b> Stratification</a></li>
<li class="chapter" data-level="9.5" data-path="transform.html"><a href="transform.html#outliers-and-censoring"><i class="fa fa-check"></i><b>9.5</b> Outliers and Censoring</a>
<ul>
<li class="chapter" data-level="9.5.1" data-path="transform.html"><a href="transform.html#outliers"><i class="fa fa-check"></i><b>9.5.1</b> Detecting Outliers</a></li>
<li class="chapter" data-level="9.5.2" data-path="transform.html"><a href="transform.html#censoring-outliers"><i class="fa fa-check"></i><b>9.5.2</b> Censoring outliers</a></li>
</ul></li>
<li class="chapter" data-level="9.6" data-path="transform.html"><a href="transform.html#ch-9-exercises"><i class="fa fa-check"></i><b>9.6</b> Ch-9 Exercises</a>
<ul>
<li class="chapter" data-level="9.6.1" data-path="transform.html"><a href="transform.html#salary-data-for-poly-sci-majors"><i class="fa fa-check"></i><b>9.6.1</b> Salary Data for Poly Sci Majors</a></li>
<li class="chapter" data-level="9.6.2" data-path="transform.html"><a href="transform.html#univariate-data-visualization-1"><i class="fa fa-check"></i><b>9.6.2</b> Univariate Data Visualization</a></li>
<li class="chapter" data-level="9.6.3" data-path="transform.html"><a href="transform.html#rescale-and-censor-data"><i class="fa fa-check"></i><b>9.6.3</b> Rescale and Censor Data</a></li>
<li class="chapter" data-level="9.6.4" data-path="transform.html"><a href="transform.html#logfit"><i class="fa fa-check"></i><b>9.6.4</b> Fit a Log-normal Distribution</a></li>
<li class="chapter" data-level="9.6.5" data-path="transform.html"><a href="transform.html#plot-fitted-vs-actual-data"><i class="fa fa-check"></i><b>9.6.5</b> Plot Fitted vs Actual Data</a></li>
<li class="chapter" data-level="9.6.6" data-path="transform.html"><a href="transform.html#transform-the-data"><i class="fa fa-check"></i><b>9.6.6</b> Transform the Data</a></li>
</ul></li>
<li class="chapter" data-level="9.7" data-path="transform.html"><a href="transform.html#ch-9-homework"><i class="fa fa-check"></i><b>9.7</b> Ch-9 Homework</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="measure.html"><a href="measure.html"><i class="fa fa-check"></i><b>10</b> Measurement</a>
<ul>
<li class="chapter" data-level="10.1" data-path="measure.html"><a href="measure.html#ch.-10-objectives"><i class="fa fa-check"></i><b>10.1</b> Ch. 10 Objectives</a></li>
<li class="chapter" data-level="10.2" data-path="measure.html"><a href="measure.html#sampling"><i class="fa fa-check"></i><b>10.2</b> Sampling</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="measure.html"><a href="measure.html#sample"><i class="fa fa-check"></i><b>10.2.1</b> Samples vs. Populations</a></li>
<li class="chapter" data-level="10.2.2" data-path="measure.html"><a href="measure.html#sample.collect"><i class="fa fa-check"></i><b>10.2.2</b> Collecting a sample</a></li>
<li class="chapter" data-level="10.2.3" data-path="measure.html"><a href="measure.html#simple-random-sampling"><i class="fa fa-check"></i><b>10.2.3</b> Simple Random Sampling</a></li>
<li class="chapter" data-level="10.2.4" data-path="measure.html"><a href="measure.html#systematic-sampling"><i class="fa fa-check"></i><b>10.2.4</b> Systematic Sampling</a></li>
<li class="chapter" data-level="10.2.5" data-path="measure.html"><a href="measure.html#stratified-sampling"><i class="fa fa-check"></i><b>10.2.5</b> Stratified Sampling</a></li>
<li class="chapter" data-level="10.2.6" data-path="measure.html"><a href="measure.html#cluster-sampling"><i class="fa fa-check"></i><b>10.2.6</b> Cluster Sampling</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="measure.html"><a href="measure.html#figures-of-merit"><i class="fa fa-check"></i><b>10.3</b> Figures of Merit</a>
<ul>
<li class="chapter" data-level="10.3.1" data-path="measure.html"><a href="measure.html#LOD"><i class="fa fa-check"></i><b>10.3.1</b> Limit of Detection &amp; Quantification</a></li>
<li class="chapter" data-level="10.3.2" data-path="measure.html"><a href="measure.html#dynamic"><i class="fa fa-check"></i><b>10.3.2</b> Dynamic Range</a></li>
<li class="chapter" data-level="10.3.3" data-path="measure.html"><a href="measure.html#precision"><i class="fa fa-check"></i><b>10.3.3</b> Precision</a></li>
<li class="chapter" data-level="10.3.4" data-path="measure.html"><a href="measure.html#bias"><i class="fa fa-check"></i><b>10.3.4</b> Bias (accuracy)</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="measure.html"><a href="measure.html#measurement-uncertainty"><i class="fa fa-check"></i><b>10.4</b> Measurement Uncertainty</a>
<ul>
<li class="chapter" data-level="10.4.1" data-path="measure.html"><a href="measure.html#repeated"><i class="fa fa-check"></i><b>10.4.1</b> Repeated Measures</a></li>
<li class="chapter" data-level="10.4.2" data-path="measure.html"><a href="measure.html#error-propagation"><i class="fa fa-check"></i><b>10.4.2</b> Error Propagation</a></li>
</ul></li>
<li class="chapter" data-level="10.5" data-path="measure.html"><a href="measure.html#ch-10-homework"><i class="fa fa-check"></i><b>10.5</b> CH-10 Homework</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="model.html"><a href="model.html"><i class="fa fa-check"></i><b>11</b> Modeling</a>
<ul>
<li class="chapter" data-level="11.1" data-path="model.html"><a href="model.html#ch.-11-objectives"><i class="fa fa-check"></i><b>11.1</b> Ch. 11 Objectives</a></li>
<li class="chapter" data-level="11.2" data-path="model.html"><a href="model.html#process-modeling"><i class="fa fa-check"></i><b>11.2</b> Process Modeling</a>
<ul>
<li class="chapter" data-level="11.2.1" data-path="model.html"><a href="model.html#assumptions"><i class="fa fa-check"></i><b>11.2.1</b> Assumptions</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="model.html"><a href="model.html#model-fitting"><i class="fa fa-check"></i><b>11.3</b> Model Fitting</a></li>
<li class="chapter" data-level="11.4" data-path="model.html"><a href="model.html#ols-regression"><i class="fa fa-check"></i><b>11.4</b> OLS Regression</a>
<ul>
<li class="chapter" data-level="11.4.1" data-path="model.html"><a href="model.html#OLS_example"><i class="fa fa-check"></i><b>11.4.1</b> Quick OLS Example</a></li>
<li class="chapter" data-level="11.4.2" data-path="model.html"><a href="model.html#OLS_assum"><i class="fa fa-check"></i><b>11.4.2</b> OLS Assumptions and Diagnostics</a></li>
</ul></li>
<li class="chapter" data-level="11.5" data-path="model.html"><a href="model.html#in-depth-example-ols-linear-regression"><i class="fa fa-check"></i><b>11.5</b> In-Depth Example: OLS Linear Regression</a>
<ul>
<li class="chapter" data-level="11.5.1" data-path="model.html"><a href="model.html#the-lm-function"><i class="fa fa-check"></i><b>11.5.1</b> The <code>lm()</code> function</a></li>
<li class="chapter" data-level="11.5.2" data-path="model.html"><a href="model.html#ols-diagnostics"><i class="fa fa-check"></i><b>11.5.2</b> OLS Diagnostics</a></li>
</ul></li>
<li class="chapter" data-level="11.6" data-path="model.html"><a href="model.html#calibration"><i class="fa fa-check"></i><b>11.6</b> Calibration</a>
<ul>
<li class="chapter" data-level="11.6.1" data-path="model.html"><a href="model.html#example-calibration"><i class="fa fa-check"></i><b>11.6.1</b> Example Calibration</a></li>
</ul></li>
<li class="chapter" data-level="11.7" data-path="model.html"><a href="model.html#ch-11-homework"><i class="fa fa-check"></i><b>11.7</b> Ch-11 Homework</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="dist.html"><a href="dist.html"><i class="fa fa-check"></i><b>12</b> Appendix: Stats &amp; Reference Distributions</a>
<ul>
<li class="chapter" data-level="12.1" data-path="dist.html"><a href="dist.html#measures-of-central-tendency"><i class="fa fa-check"></i><b>12.1</b> Measures of Central Tendency</a></li>
<li class="chapter" data-level="12.2" data-path="dist.html"><a href="dist.html#measures-of-dispersion"><i class="fa fa-check"></i><b>12.2</b> Measures of Dispersion</a></li>
<li class="chapter" data-level="12.3" data-path="dist.html"><a href="dist.html#unif_dist"><i class="fa fa-check"></i><b>12.3</b> Uniform Distribution</a>
<ul>
<li class="chapter" data-level="12.3.1" data-path="dist.html"><a href="dist.html#uniform-characteristic-plots"><i class="fa fa-check"></i><b>12.3.1</b> Uniform Characteristic Plots</a></li>
</ul></li>
<li class="chapter" data-level="12.4" data-path="dist.html"><a href="dist.html#normal_dist"><i class="fa fa-check"></i><b>12.4</b> Normal Distribution</a>
<ul>
<li class="chapter" data-level="12.4.1" data-path="dist.html"><a href="dist.html#normal-characteristic-plots"><i class="fa fa-check"></i><b>12.4.1</b> Normal Characteristic Plots</a></li>
<li class="chapter" data-level="12.4.2" data-path="dist.html"><a href="dist.html#rule"><i class="fa fa-check"></i><b>12.4.2</b> 68-95-99 rule</a></li>
</ul></li>
<li class="chapter" data-level="12.5" data-path="dist.html"><a href="dist.html#log_normal_dist"><i class="fa fa-check"></i><b>12.5</b> Log-normal Distribution</a>
<ul>
<li class="chapter" data-level="12.5.1" data-path="dist.html"><a href="dist.html#lognormal-characteristic-plots"><i class="fa fa-check"></i><b>12.5.1</b> Lognormal Characteristic Plots</a></li>
</ul></li>
<li class="chapter" data-level="12.6" data-path="dist.html"><a href="dist.html#pearson"><i class="fa fa-check"></i><b>12.6</b> Pearson Correlation Coefficient</a>
<ul>
<li class="chapter" data-level="12.6.1" data-path="dist.html"><a href="dist.html#anscombes-quartet"><i class="fa fa-check"></i><b>12.6.1</b> Anscombe’s Quartet</a></li>
</ul></li>
<li class="chapter" data-level="12.7" data-path="dist.html"><a href="dist.html#OLS"><i class="fa fa-check"></i><b>12.7</b> OLS Regression Coefficients</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Engineering Data Analysis in R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="model" class="section level1 hasAnchor" number="11">
<h1><span class="header-section-number">Chapter 11</span> Modeling<a href="model.html#model" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div class="rmdnote">
<p>
A <a href="https://www.merriam-webster.com/dictionary/model"
target="_blank"><strong><em>model</em></strong></a> is a system of
postulates, data, and inferences presented as a mathematical description
of an entity or state of affairs.
</p>
</div>
<p>In this chapter we will discuss how models are conceptualized and “fit” to represent the data we have available. Models are useful because they provide a mathematical basis for how we see the world (i.e., an explanation for the observational data we collect). This means that models can help you:</p>
<ol style="list-style-type: decimal">
<li>quantify patterns or trends in your data;</li>
<li>extrapolate your data (i.e., to guess an outcome outside the range of observed values);</li>
<li>interpolate your data (i.e., to guess an outcome within the range of observed values but not at a location where data has been observed)</li>
<li>predict future outcomes;</li>
<li>conect <strong><em>theory</em></strong> (what you think should happen) to <strong><em>observation</em></strong> (what you actually see happen);</li>
</ol>
<blockquote>
<p><span style="color: blue;"> “All models are wrong, but some are useful” - George Cox, pioneering statistician </span></p>
</blockquote>
<div id="ch.-11-objectives" class="section level2 hasAnchor" number="11.1">
<h2><span class="header-section-number">11.1</span> Ch. 11 Objectives<a href="model.html#ch.-11-objectives" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>This chapter is designed around the following learning objectives. Upon
completing this chapter, you should be able to:</p>
<ul>
<li>Describe the steps of model conceptualization, fitting, evaluation, and validation.</li>
<li>Develop and fit linear models to continuous, bi-variate data</li>
<li>Evaluate the assumptions of linear regression with visual diagnostics</li>
<li>Apply transformation techniques to meet linear model assumptions</li>
<li>Describe the process of parameter estimation using ordinary least squares</li>
</ul>
</div>
<div id="process-modeling" class="section level2 hasAnchor" number="11.2">
<h2><span class="header-section-number">11.2</span> Process Modeling<a href="model.html#process-modeling" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Figure <a href="model.html#fig:model-1">11.1</a> below provides a general process diagram for modeling (<a href="https://www.itl.nist.gov/div898/handbook/pmd/section4/pmd41.htm" target="_blank">adapted from the NIST Handbook on Statistics</a>);
these are the steps you should follow when developing a model. Even before you begin this process, however, you should ask yourself the following three questions:</p>
<ol style="list-style-type: decimal">
<li><strong><em>Why am I developing this model?</em></strong></li>
<li><strong><em>What do I hope to learn from this model?</em></strong></li>
<li><strong><em>What do I plan to do with this model?</em></strong></li>
</ol>
<p>The answer to these questions will undoubtedly guide your thinking as you move through the process steps; it’s important to have objectives and expectations at the start. Without purpose, a process model often comes up short.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:model-1"></span>
<p class="caption">
Figure 11.1: A generic process diagram for model conceptualization, development, and evaluation.
</p>
<img src="images/model_steps.png" alt="A generic process diagram for model conceptualization, development, and evaluation." width="400" />
</div>
<p>A couple points worth making about the process outline in Figure <a href="model.html#fig:model-1">11.1</a>. First, observing a process and matching your observations to your training and experience is an invaluable tool for model construction. Second, most models of “real-world things” like Newton’s work on gravity or Milliken’s model of elctron charge are empircal - that is, they are based on observation (not pure math). Purely <em>analytic</em> models exist (mostly as mathematical “proofs”) and such models don’t need data to be <em>“fit”</em> but do need data to be <em>validated</em>. Third, many people choose to validate their model with the same data they used to fit the model (using an approach like blocking or cross-validation). While I acknowledge that this approach is convenient (and sometimes the only means available), I disagree with it. You should always try to validate your model with an independent sample (better yet, with a sample that you didn’t collect). Why? Although we put a lot of emphasis on <a href="measure.html#sample.collect">“random sampling”</a>, we rarely succeed at it in the real world. Having someone else validate your model with their (independent) data will go a long way towards convincing others that your model is both <strong>useful</strong> and <strong>generalizable</strong>.</p>
<div id="assumptions" class="section level3 hasAnchor" number="11.2.1">
<h3><span class="header-section-number">11.2.1</span> Assumptions<a href="model.html#assumptions" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>An <strong><em>assumption</em></strong> is a fact or condition that is taken for granted. If you think about it, nearly every action you undertake carries assumptions. If someone throws a baseball to you and you reach out your hand to catch it, you are assuming that you will indeed make that catch. Otherwise, you would probably duck! When you walk across a high bridge, you undoubtedly assume that it will hold your weight. Sure, you might have a compelling reason to cross the bridge at any cost, but in that case you have assumed that the reason for crossing the bridge outweighs other risks. Those of us who live in Colorado have, at one point, made the incorrect assumption about our car or truck’s braking ability in the snow.</p>
<p><strong>All scientific models are based on assumptions; many of those assumptions are necessary (read: critical) for the model or theory to be “correct”.</strong></p>
<p>Although assumptions can be <em>taken for granted</em> when constructing a model or theory, that doesn’t mean they should be ignored. Indeed, evaluating the assumptions of a model (or theory) is one of the first things that you should do when developing OR evaluating OR applying it. <em>Testing assumptions</em> is the hallmark of a talented researcher, and yet, few researchers test their model assumptions regularly.</p>
<p>In this chapter, I will teach you about the assumptions of linear regression, but the take-home lesson is this: <strong><em>those who recognize and validate their assumptions will be rewarded for their efforts, prepared for what is to come, and will rarely depend on luck for success.</em></strong></p>
</div>
</div>
<div id="model-fitting" class="section level2 hasAnchor" number="11.3">
<h2><span class="header-section-number">11.3</span> Model Fitting<a href="model.html#model-fitting" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<blockquote>
<p><span style="color: blue;"> “The purpose of models is not to fit the data but to sharpen the questions.” - Samuel Karlim, mathematician and genomicist </span></p>
</blockquote>
<p>The best models are those that advance your understanding of a phenomenon so well that you soon leave the model behind, because the questions have since changed. We will not aspire to such great heights here, but it’s worth understanding how models can be <em>fit</em> to data. Model construction, fitting, and validation could represent an entire semester (or more) of work. Here, will will discuss one introductory application: fitting of a linear model using ordinary least squares (OLS). You have undoubtedly used a computer program to create a linear fit between an X and Y variable. Microsoft Excel will do this for you with two columns of data and a few simple mouse clicks. How that fit is achieved (and what assumptions underpin that fit) is what we will discuss here.</p>
</div>
<div id="ols-regression" class="section level2 hasAnchor" number="11.4">
<h2><span class="header-section-number">11.4</span> OLS Regression<a href="model.html#ols-regression" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>OLS stands for <strong>“Ordinary Least Squares”</strong>. The OLS technique is one of the most common ways to fit a linear regression. To keep things simple, let’s discuss fitting a model with a single independent variable (<span class="math inline">\(X\)</span>) as a predictor for our (dependent) outcome variable of interest (<span class="math inline">\(Y\)</span>). A model with one instance of a single independent variable means we have, at maximum, only two parameter estimates to fit: the <em>intercept</em> term when <span class="math inline">\(X = 0\)</span> (which we call <span class="math inline">\(\beta_{0}\)</span>) and the slope term for all values of <span class="math inline">\(X\)</span> (which we call <span class="math inline">\(\beta_{1}\)</span>). Thus, we are fitting a straight-line equation between two variables with the following notation:</p>
<p><span class="math display">\[Y = \beta_{0} + \beta_{1}\cdot X + \epsilon\]</span>
where:</p>
<p>    <span class="math inline">\(Y\)</span> = the dependent variable (i.e, the outcome - what we are trying to model)<br />
    <span class="math inline">\(\beta_{0}\)</span> = the intercept parameter (to be <em>fit</em> by OLS model)<br />
    <span class="math inline">\(\beta_{1}\)</span> = the slope parameter (to be <em>fit</em> by the OLS model)<br />
    <span class="math inline">\(X\)</span> = the independent variable (i.e., the predictor variable)<br />
    <span class="math inline">\(\epsilon\)</span> = the error term (i.e., what is left over; what the model doesn’t explain about <span class="math inline">\(Y\)</span>)</p>
<p>The OLS approach is straightforward: select model parameters (<span class="math inline">\(\beta_{0}\)</span>, <span class="math inline">\(\beta_{1}\)</span>) so that the model produces as little error as possible. With OLS, the overall model error is expressed as the sum of each residual value squared: a <em>sum-of-squares error</em> (SSE; explained below). Graphically, this is shown in Figure <a href="model.html#fig:OLS-anno">11.2</a>, where the solid blue circles represent the data (<span class="math inline">\(X_{i}, Y_{i}\)</span>). The grey line represents the “best fit” line that gives the smallest SSE possible. The model <strong><em>residuals</em></strong> (what are used to calculate the SSE) are denoted by vertical lines connecting the data points to the “best-fit line”. The optimization algorithm that sets the slope and intercept to minimize the sum of squares error is executed with matrix algebra, although the paramaters for simple linear regression between two variables, <span class="math inline">\(X,Y,\)</span> are easily calculated - see <a href="dist.html#OLS">here</a>.</p>
<div class="figure"><span style="display:block;" id="fig:OLS-anno"></span>
<img src="images/OLS_anno.png" alt="Graphical depiction for an OLS regression fit to minimize the sum of squared residuals"  />
<p class="caption">
Figure 11.2: Graphical depiction for an OLS regression fit to minimize the sum of squared residuals
</p>
</div>
<p>The Y values <em>predicted</em> by the model are denoted as <span class="math inline">\(\hat{Y_{i}}\)</span> (we say “Y hat”). Mathematically, each residual (<span class="math inline">\(\hat{\epsilon}_i\)</span>) is defined as:</p>
<p><span class="math display">\[\hat{\epsilon_{i}} = Y_{i} - \hat{Y_{i}}\]</span>
where:</p>
<p>    <span class="math inline">\(\hat{\epsilon_{i}}\)</span> is the residual for each (i<sup>th</sup>) observation<br />
    <span class="math inline">\(Y_{i}\)</span> represents the i<sup>th</sup> observation of the dependent variable, <span class="math inline">\(Y\)</span><br />
    <span class="math inline">\(\hat{Y_{i}}\)</span> represent the <em>predicted value</em> of <span class="math inline">\(Y_{i}\)</span> for each data point: <span class="math inline">\(\hat{Y_{i}} = \beta_{0} + \beta_{1}\cdot X_{i}\)</span></p>
<p>We use <em>vertical distance</em> to define residuals because we are trying to predict the <span class="math inline">\(Y\)</span> values, so we care only about how far away (in <span class="math inline">\(Y\)</span> space) our predictors, <span class="math inline">\(\hat{Y_{i}}\)</span>, are relative to “true” <span class="math inline">\(Y_{i}\)</span> data. Another way to say this is that OLS <em>assumes</em> that our <span class="math inline">\(X_{i}\)</span>’s are perfect observations (<span class="math inline">\(X\)</span> is assumed to be measured/known without error).</p>
<p>The error sum of squares (SSE) is then: <span class="math display">\[SSE = \sum_{i = 1}^{n} \left(\hat{\epsilon_{i}}\right)^{2}\]</span>
for all <span class="math inline">\(n\)</span> observations in the data set. The SSE is a really useful term; it represents the overall variance in the <span class="math inline">\(Y\)</span>-data that <strong><em>wasn’t</em></strong> explained by the model. Good models explain variance in your data, because variance means: changes in your data.</p>
<p>The <em>total sum of squares</em> (TSS) represents a measure of all the variability in the data:
<span class="math display">\[TSS = \sum_{i = 1}^{n} \left(Y_{i} - \overline{Y} \right)^2\]</span>
where <span class="math inline">\(\bar{Y}\)</span> is the mean of the observed <span class="math inline">\(Y\)</span> data. The SSE and the TSS will allow you to evaluate the overall model fit (<span class="math inline">\(R^{2}\)</span> - also called the model <em>Coefficient of Determination</em>), which is calculated from their ratio:
<span class="math display">\[R^2 = 1- \left(\frac{SSE}{TSS}\right)\]</span>
Note that for OLS regression with a single predictor (one <span class="math inline">\(X\)</span> variable), the Coefficient of Determination (<span class="math inline">\(R^{2}\)</span>) is identical to the square of the <a href="dist.html#pearson">Pearson Correlation Coefficient</a>.</p>
<p>The <em>total sum of squares</em> represents a measure of all of the variability in the data; the <em>residual sum of squares</em> represents a measure of the variability that remains <em>after the linear model has been applied</em>. Thus, <strong>the <span class="math inline">\(R^{2}\)</span> term represents the proportion of variability (variance) in your data that was explained by the linear model</strong>.</p>
<div class="rmdnote">
<p>
The terms “residual sum of squares” and “error sum of squares” are
interchangeable; you will see them both in the wild and they mean the
same thing.
</p>
</div>
<div id="OLS_example" class="section level3 hasAnchor" number="11.4.1">
<h3><span class="header-section-number">11.4.1</span> Quick OLS Example<a href="model.html#OLS_example" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Let’s take a quick look at an OLS example and how to interpret the results. Here is a scatterplot showing average life expectancy in various countries of the world vs. educational attainment (years spent in school) for men over the age of 25. Data source: <a href="https://www.gapminder.org/tools/#$model$markers$bubble$encoding$x$data$concept=mean_years_in_school_men_25_years_and_older&amp;source=sg&amp;space@=geo&amp;=time;;&amp;scale$domain:null&amp;zoomed:null&amp;type:null;;&amp;frame$value=2009;;;;;&amp;chart-type=bubbles&amp;url=v2">Gapminder</a>.</p>
<p>The <span style="color: skyblue;"><strong>blue line</strong></span> depicts the result of an OLS linear model between these variables (i.e., the regression of average life expectancy on average years spent in school for a country’s population).</p>
<div class="figure"><span style="display:block;" id="fig:OLS-life"></span>
<img src="11-model_files/figure-html/OLS-life-1.png" alt="Average Life Expectancy vs. Educational Attainment for Men over 25 in Counties in 2009" width="672" />
<p class="caption">
Figure 11.3: Average Life Expectancy vs. Educational Attainment for Men over 25 in Counties in 2009
</p>
</div>
There are multiple ways to run a regression model in R. The most common is to use the <code>lm()</code> function from <code>stats::</code>. This function requires you to specify the model using a <code>formula =</code> argument, followed by a <code>data =</code> argument that references a data frame. The <code>formula =</code> argument uses <em>tilde notation</em> to set the <code>Y</code> and <code>X</code> variables according the following nomenclature:
<span class="math display">\[Y=X\]</span>
<center>
<code>formula = dependent variable ~ independent variable</code>
</center>
<p><br/>
where the <code>~</code> represents the equals sign (this is because the <code>=</code> sign is reserved for assigning arguments in R, not specifying formulas). For the plot shown above, we can create a <code>linear model object</code> called <code>my_model</code> using the following code where <code>lex</code> is the column variable denoting life expectancy (in years) and <code>education</code> is the column variable denoting educational attainment (in years of school).</p>
<div class="sourceCode" id="cb349"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb349-1"><a href="model.html#cb349-1" tabindex="-1"></a>my_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">formula =</span> lex <span class="sc">~</span> education, <span class="at">data =</span> life_edu)</span></code></pre></div>
<p>The <code>lm()</code> function returns a a <code>list</code> as output. This list contains all the inputs (the data, the model) and outputs from the regression model. We will examine the list components later. For now, a simple way to examine the model results is to summarize them with a <code>summary()</code> function call. Even this summary function contains a lot of results! For now, just focus on the <code>Estimate</code> for each of the <code>Coefficients:</code> specified below. These coefficients represent the <span class="math inline">\(\beta_{0}\)</span> and <span class="math inline">\(\beta_{1}\)</span> terms that were estimated by the OLS regression.</p>
<div class="sourceCode" id="cb350"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb350-1"><a href="model.html#cb350-1" tabindex="-1"></a><span class="fu">summary</span>(my_model)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = lex ~ education, data = life_edu)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -21.7351  -4.6351   0.9926   4.5335  15.0306 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  55.2101     1.3746   40.17   &lt;2e-16 ***
## education     1.7705     0.1552   11.41   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 6.456 on 173 degrees of freedom
## Multiple R-squared:  0.4293, Adjusted R-squared:  0.426 
## F-statistic: 130.2 on 1 and 173 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Interpreting these coefficients is straightforward. Looking the <code>Coefficients:</code> table, the <span class="math inline">\(\beta_{0}\)</span> coefficient is the number listed next to <code>(Intercept)</code> and the <span class="math inline">\(\beta_{1}\)</span> coefficient (the slope term) is number listed next to the variable name <code>education</code>. Mathematically, this means that the model predicts that 0 years of education results in an average lifespan of 55.2 years (<span class="math inline">\(\beta_{0}\)</span>) for a country’s population, and each additional year of education extends the average lifespan of a country’s population by 1.77 years (<span class="math inline">\(\beta_{1}\)</span>). Other parts of the table provide the model <span class="math inline">\(R^2\)</span> and quantiles of <code>Residuals</code>, aka the model error (<span class="math inline">\(\hat{\epsilon_{i}}\)</span>).</p>
<p>Note that because these data are <em>country-wide</em> averages, they represent predictions for populations, not individuals. If you assume that your life will be extended by 1.77 years for each year you spend in school, you are falling prey to the <a href="https://en.wikipedia.org/wiki/Ecological_fallacy">ecological fallacy</a> whereby conclusions about individuals are inferred from data on groups.</p>
<p>Looking across the <code>Coefficients:</code> table, we can also see that the uncertainty for each of these coefficients has been estimated, via the <code>Std. Error</code> column (short for <em>Standard Error</em> and sometimes shown as <em>se</em> or <em>s.e.</em>). Whereas the <em>standard deviation</em> is an estimate of spread for univariate data, the <em>standard error</em> is an estimate of spread (read: precision) for the model coefficients calculated here (i.e., how variable are the estimates for (<span class="math inline">\(\beta_{0}\)</span>) and (<span class="math inline">\(\beta_{1}\)</span>).</p>
</div>
<div id="OLS_assum" class="section level3 hasAnchor" number="11.4.2">
<h3><span class="header-section-number">11.4.2</span> OLS Assumptions and Diagnostics<a href="model.html#OLS_assum" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Now that you have an idea <em>how</em> OLS works and <em>what</em> it provides, let’s talk about the assumptions of OLS linear models. I will break the assumptions of OLS linear regression into two groups: front-end and back-end. The front-end assumptions are ones that apply to the model and the data at the outset. Most of the front-end assumptions can be tested <ins>before you fit the model</ins>. The back-end assumptions are ones that you test <ins>after</ins> the model has been built - these assumptions apply to the error term (<span class="math inline">\(\epsilon\)</span>). I list each assumption below and provide a brief explanation of how to evaluate them (and why you should care about doing so).</p>
<div id="front-end-assumptions" class="section level4 hasAnchor" number="11.4.2.1">
<h4><span class="header-section-number">11.4.2.1</span> Front-end assumptions:<a href="model.html#front-end-assumptions" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<ol style="list-style-type: decimal">
<li><strong>The form of the model is linear in the coefficients.</strong>
<ul>
<li><em>Linear in the coefficients</em> means that the parameter estimates (<span class="math inline">\(\beta_{0}\)</span>, <span class="math inline">\(\beta_{1}\)</span>,…<span class="math inline">\(\beta_{n}\)</span>) all show up in the final model as being added together. An important point here is that the <strong><em>model variables do not need to be linear terms</em></strong>. You can use linear regression with non-linear predictor variables, such that the following model would be considered “linear” in the parameters: <span class="math inline">\(Y = \beta_{0} + \beta_{1}\cdot{X_{1}^{2}} + \beta_{2}\cdot{X_{2}^{3}} + \epsilon\)</span>. This model is still “linear” because the <span class="math inline">\(\beta\)</span>-terms are being added together.
<ul>
<li><em>How to check</em>: It’s easy to tell if your model is linear in the coefficients by just looking at it, since this is a structural requirement. If the <span class="math inline">\(\beta\)</span>-terms show up in non-arithmetic ways (e.g., <span class="math inline">\(\cos(\beta_{1})\cdot X^{\beta_{2}}\)</span>) then you are developing a <em>non-linear</em> model (signifying that it’s time to take a statistics course).<br />
</li>
<li><em>Why you care</em>: You model will not run (at least not correctly) if not set up correctly. Attempting to fit an OLS linear fit on a non-linear model is bad news.</li>
</ul></li>
</ul></li>
<li><strong>The model is correctly specified.</strong>
<ul>
<li>This assumption speaks to the actual variables included in the model and their form. How many independent variables are needed and to what power do you raise each (if not to the first power)? Is the function <span class="math inline">\(Y = f(X_{1},X_{2})\)</span> best modeled as <span class="math inline">\(log(Y) = \beta_{1}\cdot{X_{1}} + \beta_{2}\cdot{X_{2}}\)</span> or <span class="math inline">\(Y = \beta_{1}\cdot{X_{1}^{2}} + \beta_{2}\cdot{X_{2}^{3}}\)</span>?
<ul>
<li><em>How to check</em>: This is a tough assumption to evaluate in advance. The best way to specify the model correctly is through a combination of (1) checking the other assumptions, (2) using your experience/process knowledge to inform the model design, (3) conducting an exploratory data analysis to inform your thinking and (4) following an established model selection procedure (this last one <em>also</em> suggests that you to take a formal class on statistics).</li>
<li><em>Why you care</em>: If the model is not specified correctly it might perform poorly under validation, or, it might suggest that a variable is not important, when in fact it is!<br />
</li>
</ul></li>
</ul></li>
<li><strong>No collinearity between predictor variables.</strong>
<ul>
<li>The <em>no collinearity</em> assumption only applies when your model has more than one predictor variable (<span class="math inline">\(X_{1}\)</span>, <span class="math inline">\(X_{2}\)</span>, <span class="math inline">\(X_{3}\)</span>, etc.). An example would be using waist size (as <span class="math inline">\(X_{1}\)</span>) and body mass (as <span class="math inline">\(X_{2}\)</span>) to predict a person’s height (<span class="math inline">\(Y\)</span>). The two predictor variables (waist size and mass) are likely to be strongly correlated (more on <em>that</em> topic below).
<ul>
<li><em>How to check</em>: Run a correlation analysis on pairs of the independent variables (i.e., calculate a Pearson or Spearman correlation coefficient) and create a correlation plot matrix (a panel of <a href="eda2.html#scatt">scatterplots</a>) for all pairs of independent variables to examine <em>how</em> they are correlated.</li>
<li><em>Why you care</em>: When two or more predictor variables are highly correlated, the model will struggle to fit parameter estimates (e.g., <span class="math inline">\(\beta_{1}\)</span>, <span class="math inline">\(\beta_{2}\)</span>) for the correlated variables (read: the parameters for the correlated variables will become very sensitive to small changes in the model, which is NOT good). Note that if you don’t care about individual parameters (you only care about the model output) then violating this assumption is less important. If you do care about parameter estimates for individual predictors, the model could very well assign the wrong sign to one of the <span class="math inline">\(\beta\)</span> coefficients.</li>
</ul></li>
</ul></li>
</ol>
</div>
<div id="back-end-assumptions" class="section level4 hasAnchor" number="11.4.2.2">
<h4><span class="header-section-number">11.4.2.2</span> Back-end assumptions:<a href="model.html#back-end-assumptions" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>The <strong>error term</strong> (4) has a <strong>mean of zero</strong>, is (5) <strong>normally distributed</strong>, (6) <strong>homoscedastic</strong>, and it has (7) <strong>no autocorrelation</strong> and (8) no <strong>correlation with predictor (independent) variables</strong>. There’s a lot riding on that little error term, <span class="math inline">\(\epsilon\)</span>!</p>
<ol start="4" style="list-style-type: decimal">
<li><strong>Mean of residuals is zero</strong>.
<ul>
<li>The first requirement for a mean of zero (<span class="math inline">\(\overline{\epsilon} = 0\)</span>) will be fulfilled if the model is set up and the OLS algorithm is implemented correctly.
<ul>
<li><em>How to check</em>: calculate the model residuals and take their <code>mean()</code>.<br />
</li>
<li><em>Why you care</em>: if <span class="math inline">\(\overline{\epsilon} \neq 0\)</span>, or if <span class="math inline">\(\overline{\epsilon}\)</span> is not very close to zero, then something has gone seriously wrong with your model implementation.<br />
</li>
</ul></li>
</ul></li>
<li><strong>Residuals are normally distributed.</strong>
<ul>
<li>The general opinion among statisticians is that non-normal residuals are not a deal-breaker for your model. Non-normal residuals will affect your ability to generate confidence intervals about your estimates, but the estimates themselves should still be “BLUE”, which stands for <em>“Best Linear Unbiased Estimator”</em>.
<ul>
<li><em>How to check</em>: create a <a href="#qqplot">Q-Q plot</a> about your residuals.<br />
</li>
<li><em>Why you care</em>: violation of the normality assumption can affect the precision of your estimates.<br />
</li>
</ul></li>
</ul></li>
<li><strong>Residuals are homoscedstic (not heteroscedastic).</strong>
<ul>
<li>The term <em>“homoscedastic”</em> means to <strong>have equal variance</strong>. In the case of residuals, we want to see that their magnitude remains relatively constant as the dependent variable increases, <span class="math inline">\(Y\)</span>.
<ul>
<li><em>How to check</em>: create a <a href="eda2.html#scatt">scatterplot</a> of residuals (y-axis) vs. the fitted values, <span class="math inline">\(\hat{Y_{i}}\)</span> (x-axis; yes, I know that sounds weird to plot the Y-variable on the x-axis…). The residuals should appear evenly scattered in both directions about zero with no apparent change in magnitude as the Y variable increases.<br />
</li>
<li><em>Why you care</em>: Heteroscedasticity (one of my favorite “don’t I sound smart?” words) can affect the precision of your estimates and can also inflate your confidence in your results (read: you might think you are on to something when actually, you aren’t). If your residuals are heteroscedastic, consider applying a <a href="transform.html#transform">transformation</a> to your dependent variable to normalize the error variance. The BoxCox method is one of my favorites.<br />
</li>
</ul></li>
</ul></li>
<li><strong>No residual autocorrelation.</strong>
<ul>
<li>Autocorrelation among residuals is a strong indicator that your model is not correctly specified.
<ul>
<li><em>How to check</em>: Create <a href="eda1.html#autocorr">autocorrelation and partial autocorrelation</a> plots for your residuals. Perform a Durbin-Watson test.<br />
</li>
<li><em>Why you care</em>: Autocorrelation among residuals is a strong indicator that your model is not correctly specified.</li>
</ul></li>
</ul></li>
<li><strong>No residual correlation with independent variables.</strong>
<ul>
<li>Likewise, residual correlation with independent variables is a strong indicator that your model is not correctly specified.
<ul>
<li><em>How to check</em>: Conduct a correlation analysis on your residuals and independent variables, create <a href="#scatter">scatterplots</a> to investigate the nature of the correlation (when present).<br />
</li>
<li><em>Why you care</em>: Correlation between residuals and independent variables is a strong indicator that your model is not correctly specified. You can do better!</li>
</ul></li>
</ul></li>
</ol>
</div>
</div>
</div>
<div id="in-depth-example-ols-linear-regression" class="section level2 hasAnchor" number="11.5">
<h2><span class="header-section-number">11.5</span> In-Depth Example: OLS Linear Regression<a href="model.html#in-depth-example-ols-linear-regression" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Let’s conduct a simple linear regression with two variables that we suspect are related: a person’s waist size and their weight. We will use data collected by the US Centers for Disease Control as part of the <a href="https://www.cdc.gov/nchs/nhanes/about_nhanes.htm" target="_blank">National Health and Nutrition Examination Survey (NHANES)</a>
- a detailed annual survey of ~5,000 people living in the US.</p>
<strong>1. Specify the model</strong><br />
Before we begin let’s “look” at the data and apply some process knowledge. A scatterplot of waist size vs. body mass is shown below.
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:model1"></span>
<img src="11-model_files/figure-html/model1-1.png" alt="Scatterplot of body mass (kg) vs. waist circumfrence (cm) for US adults." width="500" />
<p class="caption">
Figure 11.4: Scatterplot of body mass (kg) vs. waist circumfrence (cm) for US adults.
</p>
</div>
<p>Clearly, a strong relationship exists between the two variables - one that we could probably approximate as linear. However, as engineers who have studied physics, we are taught that the mass of an object is the product of density, <span class="math inline">\(\rho\)</span>, and volume, <span class="math inline">\(V\)</span>:
<span class="math display">\[mass = \rho\cdot V\]</span>
Human beings are mostly water, so we can assume that density is a constant from one person to the next. Our <em>“body volume”</em> is what changes. If we approximate our bodies as cylinders, then the <em>volume</em> (and mass) of our bodies is linearly related to the product of cross-sectional area and height.
<span class="math display">\[mass = \rho\cdot Area \cdot Height\]</span>
However, we are modeling mass against waist circumference (not area), so our process knowledge tells us that waist size and body mass should NOT follow a linear relationship.
<span class="math display">\[Area = \frac{Circumference^{2}}{2\pi}\]</span>
Thus, substituting one equation into another, we arrive at the conclusion that mass should be related to the square of waist size (circumference).
<span class="math display">\[mass = \rho\cdot \frac{Circumference^{2}}{2\pi}\cdot height\]</span>
Or, another way to say this is that the square root of mass is linearly related to body circumference.
<span class="math display">\[\sqrt{mass} \sim Circumference\]</span>
<img src="images/cylinder_comic.png" style="display: block; margin: auto;" /></p>
<p>Let’s transform <span class="math inline">\(mass \rightarrow \sqrt{mass}\)</span> and then examine the two scatterplots side by side.</p>
<div class="sourceCode" id="cb352"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb352-1"><a href="model.html#cb352-1" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> data_18) <span class="sc">+</span></span>
<span id="cb352-2"><a href="model.html#cb352-2" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">x =</span> waist, <span class="at">y =</span> mass),</span>
<span id="cb352-3"><a href="model.html#cb352-3" tabindex="-1"></a>             <span class="at">alpha =</span> <span class="fl">0.1</span>,</span>
<span id="cb352-4"><a href="model.html#cb352-4" tabindex="-1"></a>             <span class="at">color =</span> <span class="st">&quot;maroon4&quot;</span>) <span class="sc">+</span></span>
<span id="cb352-5"><a href="model.html#cb352-5" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Mass, kg&quot;</span>) <span class="sc">+</span></span>
<span id="cb352-6"><a href="model.html#cb352-6" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Waist Circumference, cm&quot;</span>) <span class="sc">+</span></span>
<span id="cb352-7"><a href="model.html#cb352-7" tabindex="-1"></a>  <span class="fu">theme_classic</span>(<span class="at">base_size =</span> <span class="dv">13</span>)</span>
<span id="cb352-8"><a href="model.html#cb352-8" tabindex="-1"></a></span>
<span id="cb352-9"><a href="model.html#cb352-9" tabindex="-1"></a>p2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> data_18) <span class="sc">+</span></span>
<span id="cb352-10"><a href="model.html#cb352-10" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">x =</span> waist, <span class="at">y =</span> sqrt_mass),</span>
<span id="cb352-11"><a href="model.html#cb352-11" tabindex="-1"></a>             <span class="at">alpha =</span> <span class="fl">0.1</span>,</span>
<span id="cb352-12"><a href="model.html#cb352-12" tabindex="-1"></a>             <span class="at">color =</span> <span class="st">&quot;royalblue2&quot;</span>) <span class="sc">+</span></span>
<span id="cb352-13"><a href="model.html#cb352-13" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="fu">expression</span>(<span class="fu">sqrt</span>(mass))) <span class="sc">+</span></span>
<span id="cb352-14"><a href="model.html#cb352-14" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Waist Circumference, cm&quot;</span>) <span class="sc">+</span></span>
<span id="cb352-15"><a href="model.html#cb352-15" tabindex="-1"></a>  <span class="fu">theme_classic</span>(<span class="at">base_size =</span> <span class="dv">13</span>)</span>
<span id="cb352-16"><a href="model.html#cb352-16" tabindex="-1"></a></span>
<span id="cb352-17"><a href="model.html#cb352-17" tabindex="-1"></a><span class="fu">grid.arrange</span>(p1, p2, <span class="at">ncol =</span> <span class="dv">2</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:model-compare"></span>
<img src="11-model_files/figure-html/model-compare-1.png" alt="Side-by-side comparison of two model specifications. Does one look more linear than the other?" width="672" />
<p class="caption">
Figure 11.5: Side-by-side comparison of two model specifications. Does one look more linear than the other?
</p>
</div>
<p>Looking at the right plot in Figure <a href="model.html#fig:model-compare">11.5</a>, where <span class="math inline">\(\sqrt(mass)\)</span> is plotted, helps make the slight curvature in the left-side plot more evident. Both plots appear “mostly” linear but the one on the right “looks better”, at least to me! Our process knowledge suggests that the model on the right is better specified. Let’s fit both models and find out!</p>
<p>The NHANES data we use here is from 2017-2018 (saved as <code>bodysize.csv</code> and read into a data frame labeled: <code>data_18</code>). These data have been filtered to include adults only (<code>filter(age &gt; 18)</code>). The first few lines of data look like this:</p>
<div class="sourceCode" id="cb353"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb353-1"><a href="model.html#cb353-1" tabindex="-1"></a><span class="fu">head</span>(data_18)</span></code></pre></div>
<pre><code>## # A tibble: 6 × 7
##      id  mass waist height gender   age sqrt_mass
##   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;
## 1 93705  79.5 102.    158.      2    66      8.92
## 2 93706  66.3  79.3   176.      1    18      8.14
## 3 93708  53.5  88.2   150.      2    66      7.31
## 4 93709  88.8 113     151.      2    75      9.42
## 5 93711  62.1  86.6   171.      1    56      7.88
## 6 93712  58.9  72     173.      1    18      7.67</code></pre>
<div id="the-lm-function" class="section level3 hasAnchor" number="11.5.1">
<h3><span class="header-section-number">11.5.1</span> The <code>lm()</code> function<a href="model.html#the-lm-function" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>As shown above, the <code>lm()</code> function in R stands for <em>“linear model”</em> and will perform an OLS fit on any linear model you specify. The function requires two arguments: a <code>formula</code> (i.e., the model specification) and the <code>data</code> with which to fit that model. Formulas are specified as <code>y ~ x</code>, so our call to <code>lm()</code> looks like this for each model:</p>
<div class="sourceCode" id="cb355"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb355-1"><a href="model.html#cb355-1" tabindex="-1"></a>model1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">formula =</span> mass <span class="sc">~</span> waist, <span class="at">data =</span> data_18)</span>
<span id="cb355-2"><a href="model.html#cb355-2" tabindex="-1"></a></span>
<span id="cb355-3"><a href="model.html#cb355-3" tabindex="-1"></a>model2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">formula =</span> sqrt_mass <span class="sc">~</span> waist, <span class="at">data =</span> data_18)</span></code></pre></div>
<p>Now that we have stored each model as an object (<code>model1</code>, <code>model2</code>), so we can examine what they contain. The output of <code>lm()</code> is a list of class “lm”. If we type <code>view(model1)</code> the contents of the list become apparent.</p>
<div class="figure"><span style="display:block;" id="fig:model1-list"></span>
<img src="images/model1_list.png" alt="The `lm()` function provides a self-contained list of the model, data frame, parameter estimates, residuals, and more."  />
<p class="caption">
Figure 11.6: The <code>lm()</code> function provides a self-contained list of the model, data frame, parameter estimates, residuals, and more.
</p>
</div>
<p>As you can see, there is a wealth of information contained in the <code>lm()</code> object. The first list entry contains the model parameter estimates (<code>model1$coefficients</code>) in rank order:</p>
<ul>
<li><strong><span class="math inline">\(\beta_{0}\)</span> (model intercept):</strong> -34.37<br />
</li>
<li><strong><span class="math inline">\(\beta_{1}\)</span> (slope, <code>waist</code> coefficient):</strong> 1.16</li>
</ul>
<p>These are the primary outputs of the OLS fit; they define the line of “best fit” for which the SSE have been minimized.</p>
<p>To examine the overall fit of the model, we can call the <code>summary()</code> function with the model object as an argument. Here is the summary for <code>model1</code>:</p>
<div class="sourceCode" id="cb356"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb356-1"><a href="model.html#cb356-1" tabindex="-1"></a><span class="fu">summary</span>(model1)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = mass ~ waist, data = data_18)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -28.813  -6.725  -0.232   6.368  52.618 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -34.369905   0.816491   -42.1   &lt;2e-16 ***
## waist         1.164666   0.008034   145.0   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 9.951 on 5173 degrees of freedom
## Multiple R-squared:  0.8025, Adjusted R-squared:  0.8025 
## F-statistic: 2.102e+04 on 1 and 5173 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>and here is the summary for <code>model2</code>:</p>
<div class="sourceCode" id="cb358"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb358-1"><a href="model.html#cb358-1" tabindex="-1"></a><span class="fu">summary</span>(model2)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = sqrt_mass ~ waist, data = data_18)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -1.73672 -0.35280 -0.00426  0.35038  2.27127 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 2.7418448  0.0430512   63.69   &lt;2e-16 ***
## waist       0.0624003  0.0004236  147.31   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.5247 on 5173 degrees of freedom
## Multiple R-squared:  0.8075, Adjusted R-squared:  0.8075 
## F-statistic: 2.17e+04 on 1 and 5173 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Interestingly, both models have nearly equal fits to the data. The <span class="math inline">\(R^{2}\)</span> for <code>model1</code> is 0.8025 and the <span class="math inline">\(R^{2}\)</span> for <code>model2</code> is 0.8075 (a negligible difference in my opinion). This brings up an interesting question: <em>which model is better</em>? The answer to that question depends, of course, on (1) what you want to learn from the model, (2) what you plan to do with the model? Sound familiar?</p>
<p>Before getting to those questions, let’s continue with the modeling process by evaluating our assumptions…</p>
<p>First off, however, it always helps to visualize our model fits prior to evaluating assumptions. We expect our fits to look <em>pretty good</em> given our <span class="math inline">\(R^2\)</span> values are ~0.8.</p>
<p>We can overlay the model fits onto our scatter plots in many ways:</p>
<ul>
<li>Option 1: One way is to add a <code>geom_smooth()</code> layer to the original scatter plot. The <code>geom_smooth()</code> function is a generic curve fitting algorithm for <span class="math inline">\(X, Y\)</span> data. If we specify <code>model = "lm"</code> and <code>formula = "y ~ x"</code> as arguments, R will create identical linear models and plot those fits across the range of our data.<br />
</li>
<li>Options 2: Another way would be to call <code>geom_abline()</code> and specify as arguments:
<ul>
<li><code>slope = model1$coefficients[[2]]</code> and<br />
</li>
<li><code>intercept = model1$coefficients[[1]]</code></li>
</ul></li>
<li>Option 3: And yet a third way would be to use <code>ggplot::stat_function()</code> where we explicitly specify the model its coefficients as a linear function in R. You can learn more about each of these approaches in the help section or by typing <code>?stat_function</code> into the Console.</li>
</ul>
<div class="sourceCode" id="cb360"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb360-1"><a href="model.html#cb360-1" tabindex="-1"></a><span class="co"># note how we can add layers to existing ggplot objects</span></span>
<span id="cb360-2"><a href="model.html#cb360-2" tabindex="-1"></a>p1<span class="fl">.2</span> <span class="ot">&lt;-</span> p1 <span class="sc">+</span> </span>
<span id="cb360-3"><a href="model.html#cb360-3" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">data =</span> data_18,</span>
<span id="cb360-4"><a href="model.html#cb360-4" tabindex="-1"></a>              <span class="fu">aes</span>(<span class="at">x =</span> waist, <span class="at">y =</span> mass),</span>
<span id="cb360-5"><a href="model.html#cb360-5" tabindex="-1"></a>              <span class="at">method =</span> <span class="st">&quot;lm&quot;</span>,</span>
<span id="cb360-6"><a href="model.html#cb360-6" tabindex="-1"></a>              <span class="at">formula =</span> <span class="st">&quot;y ~ x&quot;</span>,</span>
<span id="cb360-7"><a href="model.html#cb360-7" tabindex="-1"></a>              <span class="at">color =</span> <span class="st">&quot;black&quot;</span>)</span>
<span id="cb360-8"><a href="model.html#cb360-8" tabindex="-1"></a></span>
<span id="cb360-9"><a href="model.html#cb360-9" tabindex="-1"></a>p2<span class="fl">.2</span> <span class="ot">&lt;-</span> p2 <span class="sc">+</span></span>
<span id="cb360-10"><a href="model.html#cb360-10" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">intercept =</span> model2<span class="sc">$</span>coefficients[[<span class="dv">1</span>]],</span>
<span id="cb360-11"><a href="model.html#cb360-11" tabindex="-1"></a>              <span class="at">slope =</span> model2<span class="sc">$</span>coefficients[[<span class="dv">2</span>]])</span>
<span id="cb360-12"><a href="model.html#cb360-12" tabindex="-1"></a></span>
<span id="cb360-13"><a href="model.html#cb360-13" tabindex="-1"></a><span class="fu">grid.arrange</span>(p1<span class="fl">.2</span>, p2<span class="fl">.2</span>, <span class="at">ncol =</span> <span class="dv">2</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:model-fits"></span>
<img src="11-model_files/figure-html/model-fits-1.png" alt="There are many ways in R to overlay a linear fit onto a scatter plot" width="672" />
<p class="caption">
Figure 11.7: There are many ways in R to overlay a linear fit onto a scatter plot
</p>
</div>
<p>Note that <code>geom_abline()</code> extends the line to the <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> axis limits (beyond the reach of the actual data). This type of extrapolation is sometimes frowned upon because you don’t have data out there. In the case of Figure <a href="model.html#fig:model-fits">11.7</a>, this isn’t such a big deal because we set our plot limits to closely match our data limits. We will come back to these plots later on, as we examine our model assumptions.</p>
</div>
<div id="ols-diagnostics" class="section level3 hasAnchor" number="11.5.2">
<h3><span class="header-section-number">11.5.2</span> OLS Diagnostics<a href="model.html#ols-diagnostics" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>In this section, we will run through our list of <a href="model.html#OLS_assum">OLS assumptions</a> for each of the models to prove that our models are proper and to help us decide which is better.</p>
<p><strong>Assumption #1: The form of the model is linear in the coefficients.</strong><br />
This one is easy to answer because both models were set up with only one independent variable and an intercept term: <span class="math inline">\(Y = \beta_{0} + \beta_{1}\cdot X\)</span>. The <span class="math inline">\(\beta\)</span>’s are added together so this assumption is valid for both <code>model1</code> and <code>model2</code>.</p>
<p><strong>Assumption #2: The model is correctly specified.</strong><br />
This one is hard to answer (right now) but our process knowledge (the physics of volume~mass relationships) tells us that <code>model2</code> is more representative of reality than <code>model1</code>. <em>Advantage: <code>model2</code>.</em></p>
<p><strong>Assumption #3: No collinearity between predictor variables.</strong><br />
This assumption is automatically valid because we have only one independent predictor variable in each model, ruling out any possibility of collinearity.</p>
<p><strong>Assumption #4: The error term has a mean of zero.</strong><br />
We can calculate this from our two model objects.</p>
<div class="sourceCode" id="cb361"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb361-1"><a href="model.html#cb361-1" tabindex="-1"></a><span class="fu">mean</span>(model1<span class="sc">$</span>residuals)</span></code></pre></div>
<pre><code>## [1] -1.338704e-17</code></pre>
<div class="sourceCode" id="cb363"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb363-1"><a href="model.html#cb363-1" tabindex="-1"></a><span class="fu">mean</span>(model2<span class="sc">$</span>residuals)</span></code></pre></div>
<pre><code>## [1] 4.612521e-19</code></pre>
<p>Those are pretty small numbers. Check and check.</p>
<p><strong>Assumption #5: The error term is normally distributed</strong><br />
This assumption can be checked several ways, but my preference is to create a Q-Q plot about the residuals (the Q’s stand for <em>“quantile-quantile”</em>). A Q-Q plot is a scatterplot that relates the quantile values of your data against the quantiles of an “expected distribution” - in this case the <a href="dist.html#normal_dist">normal distribution</a>. If “your data” follow the shape of the “expected data” then both datasets can be said to follow the same distribution. Thus, when you plot residuals on a “normal Q-Q plot”, you are looking for your data to fall along a straight line through the center. The <code>{ggplot}</code> package allow you to create Q-Q plots using <code>geom_qq()</code> function, which creates the plot, and <code>geom_qq_line()</code>, which adds the “expected” line to aid your eye. The <code>{stats}</code> package in base R also allows you to do this with the <code>qqnorm()</code> and the <code>qqline()</code> functions.</p>
<p>Here are the Q-Q plots for <code>model1</code> and <code>model2</code>.</p>
<div class="sourceCode" id="cb365"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb365-1"><a href="model.html#cb365-1" tabindex="-1"></a>p3 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data  =</span> model1<span class="sc">$</span>model, <span class="fu">aes</span>(<span class="at">sample =</span> model1<span class="sc">$</span>residuals)) <span class="sc">+</span></span>
<span id="cb365-2"><a href="model.html#cb365-2" tabindex="-1"></a>  <span class="fu">geom_qq</span>(<span class="at">alpha =</span> <span class="fl">0.1</span>,</span>
<span id="cb365-3"><a href="model.html#cb365-3" tabindex="-1"></a>          <span class="at">color =</span> <span class="st">&quot;maroon4&quot;</span>) <span class="sc">+</span></span>
<span id="cb365-4"><a href="model.html#cb365-4" tabindex="-1"></a>  <span class="fu">geom_qq_line</span>(<span class="at">color =</span> <span class="st">&quot;grey&quot;</span>) <span class="sc">+</span></span>
<span id="cb365-5"><a href="model.html#cb365-5" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Model 1: mass ~ waist&quot;</span>) <span class="sc">+</span></span>
<span id="cb365-6"><a href="model.html#cb365-6" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span>
<span id="cb365-7"><a href="model.html#cb365-7" tabindex="-1"></a></span>
<span id="cb365-8"><a href="model.html#cb365-8" tabindex="-1"></a>p4 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data  =</span> model2<span class="sc">$</span>model, <span class="fu">aes</span>(<span class="at">sample =</span> model2<span class="sc">$</span>residuals)) <span class="sc">+</span></span>
<span id="cb365-9"><a href="model.html#cb365-9" tabindex="-1"></a>  <span class="fu">geom_qq</span>(<span class="at">alpha =</span> <span class="fl">0.1</span>,</span>
<span id="cb365-10"><a href="model.html#cb365-10" tabindex="-1"></a>          <span class="at">color =</span> <span class="st">&quot;royalblue2&quot;</span>) <span class="sc">+</span></span>
<span id="cb365-11"><a href="model.html#cb365-11" tabindex="-1"></a>  <span class="fu">geom_qq_line</span>(<span class="at">color =</span> <span class="st">&quot;grey&quot;</span>) <span class="sc">+</span></span>
<span id="cb365-12"><a href="model.html#cb365-12" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Model 2: sqrt(mass) ~ waist&quot;</span>) <span class="sc">+</span></span>
<span id="cb365-13"><a href="model.html#cb365-13" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span>
<span id="cb365-14"><a href="model.html#cb365-14" tabindex="-1"></a></span>
<span id="cb365-15"><a href="model.html#cb365-15" tabindex="-1"></a><span class="fu">grid.arrange</span>(p3, p4, <span class="at">ncol =</span> <span class="dv">2</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:qqplot"></span>
<img src="11-model_files/figure-html/qqplot-1.png" alt="Q-Q plots of residuals for two linear models. Which set of residuals better approximates a normal distribution?" width="672" />
<p class="caption">
Figure 11.8: Q-Q plots of residuals for two linear models. Which set of residuals better approximates a normal distribution?
</p>
</div>
<p>Both models reasonable follow the expected quantile plots, although <code>model1</code> shows more deviation from normality at the upper tail. If I hadn’t seen <code>model2</code>, which looks nearly perfect, I probably would have said that <code>model1</code> was adequate. Advantage: <code>model2</code>.</p>
<p><strong>Assumption #6: The error term is homoscedastic</strong><br />
To evaluate this assumption, we create a <a href="eda2.html#scatt">scatterplot</a> of residuals vs. the fitted values, <span class="math inline">\(\hat{Y_{i}}\)</span>. Both of these data are contained in the model output lists.</p>
<div class="sourceCode" id="cb366"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb366-1"><a href="model.html#cb366-1" tabindex="-1"></a>p5 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> model1<span class="sc">$</span>model) <span class="sc">+</span> </span>
<span id="cb366-2"><a href="model.html#cb366-2" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">x =</span> model1<span class="sc">$</span>fitted.values, <span class="at">y =</span>model1<span class="sc">$</span>residuals),</span>
<span id="cb366-3"><a href="model.html#cb366-3" tabindex="-1"></a>             <span class="at">alpha =</span> <span class="fl">0.25</span>,</span>
<span id="cb366-4"><a href="model.html#cb366-4" tabindex="-1"></a>             <span class="at">color =</span> <span class="st">&quot;maroon3&quot;</span>) <span class="sc">+</span></span>
<span id="cb366-5"><a href="model.html#cb366-5" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>) <span class="sc">+</span></span>
<span id="cb366-6"><a href="model.html#cb366-6" tabindex="-1"></a>  <span class="fu">theme_classic</span>() <span class="sc">+</span></span>
<span id="cb366-7"><a href="model.html#cb366-7" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">aspect.ratio =</span> <span class="fl">0.5</span>)</span>
<span id="cb366-8"><a href="model.html#cb366-8" tabindex="-1"></a></span>
<span id="cb366-9"><a href="model.html#cb366-9" tabindex="-1"></a>p6 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> model2<span class="sc">$</span>model)<span class="sc">+</span> </span>
<span id="cb366-10"><a href="model.html#cb366-10" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">x =</span> model2<span class="sc">$</span>fitted.values, <span class="at">y =</span>model2<span class="sc">$</span>residuals),</span>
<span id="cb366-11"><a href="model.html#cb366-11" tabindex="-1"></a>             <span class="at">alpha =</span> <span class="fl">0.25</span>,</span>
<span id="cb366-12"><a href="model.html#cb366-12" tabindex="-1"></a>             <span class="at">color=</span> <span class="st">&quot;royalblue2&quot;</span>) <span class="sc">+</span></span>
<span id="cb366-13"><a href="model.html#cb366-13" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>) <span class="sc">+</span></span>
<span id="cb366-14"><a href="model.html#cb366-14" tabindex="-1"></a>  <span class="fu">theme_classic</span>() <span class="sc">+</span></span>
<span id="cb366-15"><a href="model.html#cb366-15" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">aspect.ratio =</span> <span class="fl">0.5</span>)</span>
<span id="cb366-16"><a href="model.html#cb366-16" tabindex="-1"></a></span>
<span id="cb366-17"><a href="model.html#cb366-17" tabindex="-1"></a><span class="fu">grid.arrange</span>(p5, p6, <span class="at">ncol =</span> <span class="dv">1</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:residual-plot"></span>
<img src="11-model_files/figure-html/residual-plot-1.png" alt="Residuals vs. fitted values as a check for homoscedasticity." width="672" />
<p class="caption">
Figure 11.9: Residuals vs. fitted values as a check for homoscedasticity.
</p>
</div>
<p>Looking at these plots, the residuals don’t show major changes across the range of fitted values (for both plots) - this is a good outcome because it implies the residuals are homoscedastic. There are slight differences between the two models, however. For example, <code>model1</code> tends to have positive residuals at low and high values of <span class="math inline">\(\hat{Y_{i}}\)</span>, whereas, <code>model2</code> seems to have more constant error across the range of <span class="math inline">\(\hat{Y_{i}}\)</span>. Boring residuals are what you want. <em>Advantage: <code>model2</code>.</em></p>
<p><strong>Assumption 7: No autocorrelation among residuals</strong>
This assumption is evaluated by making a <a href="eda1.html#autocorr">partial autocorrelation plot</a> of your residuals. We will accomplish these plots using <code>pacf()</code> function from the <code>{stats}</code> package.</p>
<div class="sourceCode" id="cb367"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb367-1"><a href="model.html#cb367-1" tabindex="-1"></a>stats<span class="sc">::</span><span class="fu">pacf</span>(model1<span class="sc">$</span>residuals, </span>
<span id="cb367-2"><a href="model.html#cb367-2" tabindex="-1"></a>            <span class="at">main =</span> <span class="st">&quot;Model 1 Partial Autocorrelation Plot&quot;</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:resid-autocorr-1"></span>
<img src="11-model_files/figure-html/resid-autocorr-1.png" alt="Partial autocorrelation plots of residuals." width="672" />
<p class="caption">
Figure 11.10: Partial autocorrelation plots of residuals.
</p>
</div>
<div class="sourceCode" id="cb368"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb368-1"><a href="model.html#cb368-1" tabindex="-1"></a>stats<span class="sc">::</span><span class="fu">pacf</span>(model2<span class="sc">$</span>residuals, </span>
<span id="cb368-2"><a href="model.html#cb368-2" tabindex="-1"></a>            <span class="at">main =</span> <span class="st">&quot;Model 2 Partial Autocorrelation Plot&quot;</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:resid-autocorr-2"></span>
<img src="11-model_files/figure-html/resid-autocorr-2.png" alt="Partial autocorrelation plots of residuals." width="672" />
<p class="caption">
Figure 11.11: Partial autocorrelation plots of residuals.
</p>
</div>
<p>Neither plot shows a <em>strong</em> degree of autocorrelation, though both plots suggest that lag-5 autocorrelation is borderline significant (moreso for <code>model1</code>). Autocorrelation among the residuals suggests that your model is not correctly specified and these results suggest that <code>model2</code> is slightly better specified than <code>model1</code>. Perhaps something is missing from these models?</p>
<p><strong>Assumption 8: Residuals are not correlated with predictor variables.</strong>
This assumption can be evaluated through a correlation analysis. The <code>cor()</code> function from the <code>{stats}</code> package allows you to calculate correlation coefficients (e.g., Pearson, Spearman) among variables in a data frame. If you supply a data frame as an argument to <code>cor()</code> it will calculate correlations among all possible variable combinations. Otherwise, you can supply it with two vectors: <code>x =</code> and <code>y =</code>.</p>
<div class="sourceCode" id="cb369"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb369-1"><a href="model.html#cb369-1" tabindex="-1"></a><span class="fu">cor</span>(<span class="at">x =</span> model1<span class="sc">$</span>residuals, </span>
<span id="cb369-2"><a href="model.html#cb369-2" tabindex="-1"></a>    <span class="at">y =</span> model1<span class="sc">$</span>model[,<span class="dv">2</span>],</span>
<span id="cb369-3"><a href="model.html#cb369-3" tabindex="-1"></a>    <span class="at">method =</span> <span class="st">&quot;pearson&quot;</span> )</span></code></pre></div>
<pre><code>## [1] 9.023795e-18</code></pre>
<div class="sourceCode" id="cb371"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb371-1"><a href="model.html#cb371-1" tabindex="-1"></a><span class="fu">cor</span>(<span class="at">x =</span> model2<span class="sc">$</span>residuals, </span>
<span id="cb371-2"><a href="model.html#cb371-2" tabindex="-1"></a>    <span class="at">y =</span> model1<span class="sc">$</span>model[,<span class="dv">2</span>],</span>
<span id="cb371-3"><a href="model.html#cb371-3" tabindex="-1"></a>    <span class="at">method =</span> <span class="st">&quot;pearson&quot;</span> )</span></code></pre></div>
<pre><code>## [1] 4.738305e-17</code></pre>
<p>The correlation coefficients are both nearly zero, so this last assumption is validated.</p>
<p><strong><em>Which model is best?</em></strong>
Both models explained ~80% of the variance in our dependent variable. Based on our process knowledge and the fit diagnostics, we can conclude that <code>model2</code> is better specified than <code>model1</code>. In examining our process knowledge and the residuals, however, we cannot help but wonder if a better model exists out there to predict body mass based on measurement variables?</p>
<div class="rmdnote">
<p>
R has a quick and easy way to explore model fits by calling
<code>plot()</code> and using your model object as the argument. Try it
out!
</p>
</div>
</div>
</div>
<div id="calibration" class="section level2 hasAnchor" number="11.6">
<h2><span class="header-section-number">11.6</span> Calibration<a href="model.html#calibration" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Calibration is a common technique in science and engineering used to aid
measurement. To <em>calibrate</em> an instrument means to compare its measurements
to those of a better one (when measuring the same thing). What qualifies as a better instrument? That depends on on the thing being measured but we usually utilize
metrics like <em><a href="measure.html#precision">precision</a></em>, <em><a href="measure.html#bias">bias</a></em>, <em>linearity</em>, and <em><a href="measure.html#dynamic">dynamic range</a></em> to judge whether one instrument is <em>better</em> than another. In this section, we will outline the approach for calibration using linear modeling as a tool.</p>
<p>The following steps are needed to calibrate an instrument that reports continuous readings:</p>
<ol style="list-style-type: decimal">
<li><strong>Decide on the form of the</strong> <strong><em>reference</em></strong> (to which your instrument is
being compared). The two most common approaches are to use either a
<em>standard reference measurement</em> or a <em>standard reference material</em>.
<ul>
<li>To use a <em>standard reference measurement</em> means to use a better (trusted)
instrument to perform your calibration. The term <strong>standard reference</strong> in
science or engineering means “commonly accepted as a best available
technique”. Standard reference instruments often come with some sort of
certification of authenticity or performance (i.e., <em>accurate to within X %</em>
<em>and precise to within Y %</em>).<br />
</li>
<li>To use a <em>standard reference material</em> means to have known quantities of the
thing being measured. Standard reference materials are nice because, if you
have them, then you don’t need a better instrument with which to perform the
calibration. Unfortunately, standard reference materials are not always available
(commercially) and, when they are, tend to be expensive.<br />
</li>
</ul></li>
<li><strong>Decide on the <em>range</em> and <em>number of measurements</em> needed for the calibration</strong>.
Although a calibration can technically be performed with just a single data
point, we often want to confirm that our measurement device can handle a wide
range of levels. Thus, the range should span all values of the
<em>thing being measured</em> that you expect to encounter, and then some. If, for
example, you wanted to measure the mass of objects between 50 and 100g, you
might consider calibrating your instrument from 0 to 150g. The range and number
of measurements needed to perform a calibration is a judgment call; there is
no <em>“correct”</em> number of samples needed to perform a calibration. That said,
I can offer some advice:
<ul>
<li>The calibration range should not exceed the <em><a href="measure.html#dynamic">dynamic range</a></em>
of your instrument (if known), nor should it greatly exceed the range of
measurements you expect to encounter (the latter is a waste of time/effort).</li>
<li>If you wish to check the calibration of a device (that you otherwise tend
to trust), then a 6-point calibration is common (a “zero point” plus five
measurement points across the selected range).</li>
<li>When performing a calibration, it’s a good idea to take <em>multiple samples</em>
at each level of interest. These repeated measures can be used to estimate
method <em><a href="measure.html#precision">precision</a></em>. I recommend 3-4 repeats at each level, which
with a 6-point calibration, would give you 20 data points.</li>
<li>If you wish to establish or evaluate figures of merit like
<em><a href="measure.html#dynamic">dynamic range</a></em> or <em>linearity</em> of your measurement method, you
likely need a more comprehensive calibration dataset.<br />
</li>
<li>If the data are easy to obtain, a larger sample size is always better.
In other words, if it takes a few seconds or under a minute to collect a
single data point - don’t stop at 6 levels; make it 60! This is especially true
if the calibration is non-linear.</li>
</ul></li>
<li><strong>Collect the calibration data.</strong> This step is relatively straightforward.
Set up an experiment so that you can take the required number of
measurements with your instrument.
<ul>
<li>Note that a <em>randomized</em> measurement strategy is preferred.<br />
</li>
</ul></li>
<li><strong>Create a calibration curve.</strong> Fit a linear model between the instrument
being calibrated (y-axis) and your reference data (x-axis). Check model
assumptions.<br />
</li>
<li><strong>Evaluate method performance.</strong> Decide on whether your instrument is
biased.
<ul>
<li>Is the slope of the line equal to 1.0?</li>
<li>Is the intercept of the model fit equal to 0?</li>
<li>Do the residuals show a pattern with changing sample magnitude?</li>
<li>Are the residuals correlated with something (i.e., another variable)?<br />
Calculate instrument precision and linearity. Decide on whether the dynamic
range of the instrument was exceeded by any of calibration levels.</li>
</ul></li>
</ol>
<div id="example-calibration" class="section level3 hasAnchor" number="11.6.1">
<h3><span class="header-section-number">11.6.1</span> Example Calibration<a href="model.html#example-calibration" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>In this example, we will evaluate the calibration of a low-cost instrument
designed to measure <em>aerosol optical depth</em>, or AOD. The term aerosol optical
depth is a term in atmospheric science that describes whether air pollution
contributes to loss of visibility in the atmosphere (it is like a measure of
haziness of the sky). We often experience high levels of AOD in Colorado when
smoke from wildfires shows up (and that happens more often each year).</p>
<div class="sourceCode" id="cb373"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb373-1"><a href="model.html#cb373-1" tabindex="-1"></a>cal_data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="at">file =</span> <span class="st">&quot;./data/cal_aod.csv&quot;</span>, <span class="at">col_names =</span> <span class="cn">TRUE</span>)</span>
<span id="cb373-2"><a href="model.html#cb373-2" tabindex="-1"></a></span>
<span id="cb373-3"><a href="model.html#cb373-3" tabindex="-1"></a><span class="fu">head</span>(cal_data)</span></code></pre></div>
<pre><code>## # A tibble: 6 × 4
##   wave  time_r               amod aeronet
##   &lt;chr&gt; &lt;dttm&gt;              &lt;dbl&gt;   &lt;dbl&gt;
## 1 440nm 2020-08-15 20:05:54 0.457   0.445
## 2 440nm 2020-08-15 20:20:54 0.457   0.440
## 3 440nm 2020-08-15 20:35:54 0.432   0.394
## 4 440nm 2020-08-15 20:50:54 0.391   0.381
## 5 440nm 2020-08-15 21:05:54 0.367   0.376
## 6 440nm 2020-08-15 21:20:54 0.355   0.346</code></pre>
<p>Closer examination of the data indicates that we have two instruments (<code>amod</code> and <code>aeronet</code>) that are measuring the same quantity: <em>aerosol optical depth</em>. Thus, we have the same type of observation being reported in two different columns. This means we need to tidy this data frame!</p>
<div class="sourceCode" id="cb375"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb375-1"><a href="model.html#cb375-1" tabindex="-1"></a>tidy_cal <span class="ot">&lt;-</span> cal_data <span class="sc">%&gt;%</span></span>
<span id="cb375-2"><a href="model.html#cb375-2" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols =</span> <span class="fu">c</span>(<span class="st">&quot;amod&quot;</span>, <span class="st">&quot;aeronet&quot;</span>), </span>
<span id="cb375-3"><a href="model.html#cb375-3" tabindex="-1"></a>               <span class="at">names_to =</span> <span class="st">&quot;instrument&quot;</span>, </span>
<span id="cb375-4"><a href="model.html#cb375-4" tabindex="-1"></a>               <span class="at">values_to =</span> <span class="st">&quot;aod&quot;</span>)</span>
<span id="cb375-5"><a href="model.html#cb375-5" tabindex="-1"></a></span>
<span id="cb375-6"><a href="model.html#cb375-6" tabindex="-1"></a><span class="fu">head</span>(tidy_cal)</span></code></pre></div>
<pre><code>## # A tibble: 6 × 4
##   wave  time_r              instrument   aod
##   &lt;chr&gt; &lt;dttm&gt;              &lt;chr&gt;      &lt;dbl&gt;
## 1 440nm 2020-08-15 20:05:54 amod       0.457
## 2 440nm 2020-08-15 20:05:54 aeronet    0.445
## 3 440nm 2020-08-15 20:20:54 amod       0.457
## 4 440nm 2020-08-15 20:20:54 aeronet    0.440
## 5 440nm 2020-08-15 20:35:54 amod       0.432
## 6 440nm 2020-08-15 20:35:54 aeronet    0.394</code></pre>
<p>Before we begin our calibration, let’s examine the data using EDA techniques. We know that the <code>amod</code> column represents the instrument to be calibrated and the <code>aeronet</code> instrument represent the standard reference.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:aod-eda-4plot"></span>
<img src="images/aod_eda_4plot.png" alt="A 4-plot EDA of our AOD Calibration Data"  />
<p class="caption">
Figure 11.12: A 4-plot EDA of our AOD Calibration Data
</p>
</div>
<p>Let’s fit a linear model between <code>aeronet</code> AOD as the independent variable and <code>amod</code> AOD as the dependent variable. Note that while we decided to <code>tidy</code> the data frame for making our EDA plots, we may not want tidy data for our calibration fit. That’s because, with calibration, we are treating the two AOD instruments as separate variables (i.e., <code>x</code> and <code>y</code>). Thus, we will call upon the non-tidy <code>cal_data</code> to specify a <code>y ~ x</code> formula in the <code>lm()</code> function below. And once we fit the model, we create a <code>summary()</code> object to examine fit statistics, coefficients, and confidence intervals.</p>
<div class="sourceCode" id="cb377"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb377-1"><a href="model.html#cb377-1" tabindex="-1"></a>aod.fit <span class="ot">&lt;-</span> <span class="fu">lm</span>(amod <span class="sc">~</span> aeronet, <span class="at">data =</span> cal_data)</span>
<span id="cb377-2"><a href="model.html#cb377-2" tabindex="-1"></a></span>
<span id="cb377-3"><a href="model.html#cb377-3" tabindex="-1"></a>aod.summary <span class="ot">&lt;-</span> <span class="fu">summary</span>(aod.fit)</span>
<span id="cb377-4"><a href="model.html#cb377-4" tabindex="-1"></a></span>
<span id="cb377-5"><a href="model.html#cb377-5" tabindex="-1"></a>aod.summary</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = amod ~ aeronet, data = cal_data)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.07646 -0.02227 -0.01154  0.00454  0.73319 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  0.07251    0.01565   4.633 1.44e-05 ***
## aeronet      0.92344    0.01597  57.832  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.08844 on 77 degrees of freedom
## Multiple R-squared:  0.9775, Adjusted R-squared:  0.9772 
## F-statistic:  3345 on 1 and 77 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>The fit itself can be visualized using <code>ggplot2::geom_smooth()</code> with an argument of <code>method = "lm"</code>. Note also, that we can also add fit statistics to the plot by indexing list entries from the <code>aod.summary</code> list within a call to <code>ggplot2::annotate("text")</code>. This is useful because, if you change your model/fit, your text results will automatically update within the figure.</p>
<div class="sourceCode" id="cb379"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb379-1"><a href="model.html#cb379-1" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> cal_data,</span>
<span id="cb379-2"><a href="model.html#cb379-2" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x =</span> aeronet, <span class="at">y =</span> amod)) <span class="sc">+</span></span>
<span id="cb379-3"><a href="model.html#cb379-3" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">formula =</span> y <span class="sc">~</span> x,</span>
<span id="cb379-4"><a href="model.html#cb379-4" tabindex="-1"></a>              <span class="at">method =</span> <span class="st">&quot;lm&quot;</span>,</span>
<span id="cb379-5"><a href="model.html#cb379-5" tabindex="-1"></a>              <span class="at">linewidth =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb379-6"><a href="model.html#cb379-6" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.25</span>,</span>
<span id="cb379-7"><a href="model.html#cb379-7" tabindex="-1"></a>             <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb379-8"><a href="model.html#cb379-8" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Aeronet AOD&quot;</span>) <span class="sc">+</span></span>
<span id="cb379-9"><a href="model.html#cb379-9" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;AMOD AOD&quot;</span>) <span class="sc">+</span></span>
<span id="cb379-10"><a href="model.html#cb379-10" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">&quot;text&quot;</span>, <span class="at">x =</span> <span class="fl">0.5</span>, <span class="at">y =</span> <span class="fl">1.5</span>, </span>
<span id="cb379-11"><a href="model.html#cb379-11" tabindex="-1"></a>           <span class="at">label =</span> <span class="fu">paste</span>(<span class="st">&quot;Y = &quot;</span>, </span>
<span id="cb379-12"><a href="model.html#cb379-12" tabindex="-1"></a>                         <span class="fu">round</span>(aod.summary<span class="sc">$</span>coefficients[[<span class="dv">2</span>,<span class="dv">1</span>]], <span class="dv">2</span>),</span>
<span id="cb379-13"><a href="model.html#cb379-13" tabindex="-1"></a>                         <span class="st">&quot;X + &quot;</span>, <span class="fu">round</span>(aod.summary<span class="sc">$</span>coefficients[[<span class="dv">1</span>,<span class="dv">1</span>]], <span class="dv">2</span>),</span>
<span id="cb379-14"><a href="model.html#cb379-14" tabindex="-1"></a>                         <span class="st">&quot;</span><span class="sc">\n</span><span class="st"> R^2 = &quot;</span>,</span>
<span id="cb379-15"><a href="model.html#cb379-15" tabindex="-1"></a>                         <span class="fu">round</span>(aod.summary<span class="sc">$</span>r.squared, <span class="dv">3</span>))) <span class="sc">+</span></span>
<span id="cb379-16"><a href="model.html#cb379-16" tabindex="-1"></a>  <span class="fu">coord_fixed</span>() <span class="sc">+</span></span>
<span id="cb379-17"><a href="model.html#cb379-17" tabindex="-1"></a>  <span class="fu">theme_bw</span>(<span class="at">base_size =</span> <span class="dv">12</span>)</span></code></pre></div>
<p><img src="11-model_files/figure-html/aod-scatterplot-1.png" width="672" /></p>
<p>Note the one outlier present in the scatterplot. Does this outlier influence the result of the calibration? How could you evaluate that question?</p>
</div>
</div>
<div id="ch-11-homework" class="section level2 hasAnchor" number="11.7">
<h2><span class="header-section-number">11.7</span> Ch-11 Homework<a href="model.html#ch-11-homework" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>This homework will give you experience with fitting OLS linear models and testing model assumptions.</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="measure.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="dist.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
